### ISSUE TITLE
Feature Extraction with NeMo ASR Pipeline without Conformer Training

### ISSUE THREAD

**Issue by csetanmayjain** [NVIDIA/NeMo#10036]
**Issue:**

I want to run the NeMo ASR pipeline to analyze the features using different parameters, datasets, and strategies. However, I do not want to run the conformer training. Instead, I only want to extract the features from the input JSON files and store them.

**Current Understanding:**

From my understanding, the current pipeline flow is as follows:

```
For each batch:
    extract features -> apply augmentation (if required) -> train -> validation
```

**Requirement:**

I need to comment out or disable the training & further parts so that the pipeline loops back to the next batch to continue feature extraction. Despite reviewing various parts of the internal code pipeline, I am unable to pinpoint where and how to make these changes.

**Version:**

NeMo version: 1.12.0rc0 (I know it's pretty old, but I have already performed a few experiments using it, so I don't want to change anything.)
Pytorch Lightning: 1.7.4

**Request for Help:**

Could you please guide me on how to disable the training & further portion while ensuring that the feature extraction continues to function as required?

Thank you.

**Comment by nithinraok** [comment]
Hi, since you want to do run only inference, you could modify the prediction_step in [model code](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/models/ctc_models.py#L572) and run .predict on any model (that uses the feature extractor you are looking for) 
Reference: https://lightning.ai/docs/pytorch/stable/deploy/production_basic.html
