### ISSUE TITLE
[Question] Normalization value

### ISSUE THREAD

**Issue by khursani8** [NVIDIA/NeMo#1203]
I'm following this [tutorial 02_Online_ASR_Microphone_Demo](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/02_Online_ASR_Microphone_Demo.ipynb) and wondering where normalization constant coming from, if I'm using different dataset should I change it to other value?

**Comment by titu1994** [comment]
Sorry for the delay, wanted to polish up the notebook.

The normalization constant is computed for a specific dataset, so if the model has been trained on a different dataset then the constant values need to be changed. 

The global mean and std vectors can be computed for a given normalization scheme ("per_feature", "all_features") by using [the following notebook](https://gist.github.com/titu1994/8c8d478a917cf62a6acd0f40af779f77).

You will note that the constants are slightly different for just Librispeech vs what the notebook displays. This is because the QuartzNet model was trained on a combination of Librispeech as well as other datasets, so the normalization constants are slightly different.

**Comment by khursani8** [comment]
Thanks, the notebook really helpful for me :)
