### ISSUE TITLE
Incompatible SAMPLE_RATE

### ISSUE THREAD

**Issue by vinayphadnis** [NVIDIA/NeMo#1279]
**Describe the bug**

Arises when a microphone of a different sample frequency is used to run `/tutorials/02_Online_ASR_Microphone_Demo.ipynb`
Working on a fix as well!
**Steps/Code to reproduce bug**

run the ipython notebook found at `/tutorials/02_Online_ASR_Microphone_Demo.ipynb`
at the last cell. a SAMPLE_RATE of 16000 or 16khz is expected. This cannot be the case always. A simple approach might be to transform the input frequency to the expected frequency using LCM -> Upscaling -> Downscaling. Working on a PR for the same

**Comment by okuchaiev** [comment]
this notebook was written for a models which we distributed and those are in 16Khz.
You are right that different sampling rate won't work there and re-sampling would be needed. But this looks more like a feature request to add to the notebook rather than bug to me. Feel free to send a PR with it. 
Closing this issue as this is not a bug
