### ISSUE TITLE
BeamSearchDecoderWithLM, TypeError: Number of output arguments

### ISSUE THREAD

**Issue by d2sys** [NVIDIA/NeMo#1354]
**Describe the bug**

Traceback (most recent call last):
  File "speech_to_text_beamsearch.py", line 141, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "speech_to_text_beamsearch.py", line 122, in main
    res = beam_search_lm.forward(log_probs=log_probs, log_probs_length=log_probs_len)
  File "/opt/conda/lib/python3.6/site-packages/nemo_toolkit-1.0.0b2-py3.6.egg/nemo/core/classes/common.py", line 513, in __call__
    instance._attach_and_validate_output_types(output_types=output_types, out_objects=outputs)
  File "/opt/conda/lib/python3.6/site-packages/nemo_toolkit-1.0.0b2-py3.6.egg/nemo/core/classes/common.py", line 161, in _attach_and_validate_output_types
    len(out_container), len(output_types)
TypeError: Number of output arguments provided (4) is not as expected (1)

**Steps/Code to reproduce bug**

My batch size is 4, I'm trying to use beam search decoder

![image](https://user-images.githubusercontent.com/33082061/97324583-a946d380-187a-11eb-844f-299b8df402a4.png)

**Expected behavior**

When I remove typecheck [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/modules/beam_search_decoder.py#L87), it works fine.

**Comment by bartolootrit** [comment]
Changing [here](https://github.com/NVIDIA/NeMo/blob/6796faa62e9d9c42ee86f860f1a79d8db15561ae/nemo/collections/asr/modules/beam_search_decoder.py#L57) `return {"predictions": NeuralType(('B', 'T'), PredictionsType())}` to `return {"predictions": [NeuralType(('B', 'T'), PredictionsType())]}` (note the square brackets) also helps due to [this](https://github.com/NVIDIA/NeMo/blob/6796faa62e9d9c42ee86f860f1a79d8db15561ae/nemo/core/classes/common.py#L285) check, as the comment "the provided NeuralTypes {} should enable container support (add '[]' to the NeuralType definition)" [here](https://github.com/NVIDIA/NeMo/blob/6796faa62e9d9c42ee86f860f1a79d8db15561ae/nemo/core/classes/common.py#L296) suggests. What is a correct way to fix this output type definition?
