### ISSUE TITLE
Fine-tuning of VAD EncDecClassificationModel fails while computing classification accuracy

### ISSUE THREAD

**Issue by yasumori** [NVIDIA/NeMo#1581]
**Describe the bug**

I tried to fine-tune EncDecClassificationModel with my labels and encountered `TypeError: only integer tensors of a single element can be converted to an index`. The error came from `NeMo/nemo/collections/common/metrics/classification_accuracy.py`

**Steps/Code to reproduce bug**

```python3
 vad_model = EncDecClassificationModel.from_pretrained(model_name="MatchboxNet-VAD-3x2")
 my_labels = ['a', 'b', 'c']
 vad_model.change_labels(my_labels)
 vad_model.setup_training_data(
            train_data_config={
                'vad_stream': True,
                'sample_rate': 16000,
                'manifest_filepath': my_train_path,
                'labels': my_labels,
                'num_workers': 10,
                'shuffle': True,
                'time_length': 0.67,
                'shift_length': 0.01,
                'trim_silence': False,
            }
        )
 trainer = pl.Trainer(gpus=[0])
 trainer.fit(vad_model)
```

**Environment overview (please complete the following information)**

 - pip install using `reinstall.sh` in the NeMo repository

**Environment details**

- OS version Debian GNU/Linux 10
- PyTorch version 1.7.1
- Python version 3.8.6

**Comment by titu1994** [comment]
This is an issue due to Pytorch 1.7.1 changes regarding how puts are casted inside torch.tensor(). There is currently a PR to update NeMo to 1.7.1 here - https://github.com/NVIDIA/NeMo/pull/1579

However, there are other pressing issues before that PR can be merged, and it is unlikely to be merged in a short time. 

In the interim, you could revert to 1.7, use the b3 branch, or you can clone the Nemo main branch repo and apply the one line fix here - https://github.com/NVIDIA/NeMo/pull/1579/files#diff-403adc4a04aa5494044dea63fc59969e52d78c32e6a0ab4518a7c5556c5e6991R89

**Comment by yasumori** [comment]
Thanks for your quick reply!
I've applied the one line fix and indeed everything looks good.
