### ISSUE TITLE
kaldi wav.scp and text to manifest support?

### ISSUE THREAD

**Issue by qmpzzpmq** [NVIDIA/NeMo#1640]
Hi, guys. I am new to NeMo.
And I still reusing the data augment in Kaldi, since there have a lot data prepare script.
is it possible to read pipeline data in NeMo, I already wrote a script generate Manifest .json file from wav.scp and text file in kaldi stype dataset. But it only work for .wav not pipeline data.
And I found (https://github.com/NVIDIA/NeMo/issues/743)  KaldiFeatureDataLayer already removed. Do you guys have any plan for these?

**Comment by jprobichaud** [comment]
Adding a `me too` comment here.  I'm actually interested in loading features archives computed by kaldi (like fbank).  This is a feature very useful we find in other toolkits like ESPnet for example.  Is there some documentation or some guidelines how one would implement that?

**Comment by qmpzzpmq** [comment]
@jprobichaud I already fixed here
https://github.com/NVIDIA/NeMo/pull/1644

**Comment by jprobichaud** [comment]
@qmpzzpmq Thanks for your reply.  This is useful for loading audio that can come from transformation, but that assumes that the entire audio will be one "segment".  The kaldi feature data layer allowed if I read properly to read in extracted features for each segments (one audio file could be split in multiple shorter segments.

It's already nice to have the pipe reading available.  Thanks for that!  I still wonder if reading audio + segment or raw features will be possible again in the future or if that was deem not useful.

**Comment by fayejf** [comment]
Hi @jprobichaud and @qmpzzpmq Thanks for your requests and contributions.

Yes we think the external features (like fbank) is quite useful. Due to some maintenance reason, we don't have KaldiFeatureLayer now. But we are working on ExternalFeatureDataloader that reads the stored feature (in pickle) and we will provide the script to extract and store it to pickle files.  Hope this would give more flexibility. We might support reading from feature.scp as well later. 

>  extracted features for each segments (one audio file could be split in multiple shorter segments.

Like [feat1, feat2, feat3] corresponding to [utt1, utt2, utt3]? @jprobichaud  could you elaboration more so we can understand your idea clearly?

**Comment by qmpzzpmq** [comment]
@jprobichaud 
using "utils/data/extract_wav_segments_data_dir.sh"
