### ISSUE TITLE
Language Model - Old Tutorial links[Question]

### ISSUE THREAD

**Issue by ulucsahin** [NVIDIA/NeMo#1676]
Hello, I am currently training a QuartzNet15x5 model for speech recognition. As far as I know this uses greedy decoder by default. I want to use a language model to achieve better WER if possible. I have 2 questions:

1) If I want to use a language model instead of greedy decoder, should I restart my training and train language model in parallel with my encoder-decoder, or does language model part act like a separate entity which can be plugged in after training?

2) I am trying to follow tutorials but most of the links give me 404 error because of the structure change in this repository. Do old tutorials not work or can I safely follow them? For example, I couldn't find the tutorial given in this link:
https://nvidia.github.io/NeMo/asr/tutorial.html#evaluation-with-language-model

Thanks.

**Comment by michael-so** [comment]
Hi, is there any update on this?

I would also like to ask if it's possible to add a language model in this notebook :
https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb

I would like to add my language model to train my data in order to achieve better WER, so far I could not find any tutorial on this.

Looking forward for your replies,

Thanks.

**Comment by titu1994** [comment]
Documentation for language modelling with ASR models is available here - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html
