### ISSUE TITLE
cannot import name 'LabelStudioMLBase' from 'label_studio.ml'

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#1972]
I tried to run LabelStudio notebook but gave me this error 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-ddf1c99aa95c> in <module>
      1 import nemo
      2 import nemo.collections.asr as nemo_asr
----> 3 from label_studio.ml import LabelStudioMLBase
      4 
      5 

ImportError: cannot import name 'LabelStudioMLBase' from 'label_studio.ml' (/home/SAM/anaconda3/envs/nemo/lib/python3.7/site-packages/label_studio/ml/__init__.py)

what could be the problem?

**Comment by smoreface** [comment]
Thanks for this issue @Omarnabk! We moved the Label Studio ML backend to a new repo, so the import path needs to be updated, and you'll also need to install the ML backend in addition to Label Studio.

a PR to fix this in the Jupyter notebook is coming soon, but in the meantime you can do the following:
1. After you install label studio, install the ML backend: `pip install git+git://github.com/heartexlabs/label-studio-ml-backend.git#egg=label-studio-ml` (soon there will be a proper label-studio-ml pip package but you can use this command in the meantime).
2. update the import statement to import `from label_studio_ml` instead of `from label_studio.ml`

let us know if you have any more questions!

**Comment by okuchaiev** [comment]
https://github.com/NVIDIA/NeMo/pull/1989 should fix it.
