### ISSUE TITLE
Which labels are required to use in tacotron2.yaml configuration for none English languages [TTS]?

### ISSUE THREAD

**Issue by ican24** [NVIDIA/NeMo#203]
Dear Team,

I may suppose that the original letters and characters in UTF8 encoding are required in labels of the tacotron configuration file for none English languages, but as I see  in your sample for Chinese Mandarin language (tacotron2_mandarin.yaml) the latin characteres are used.

`labels: [' ', '!', ',', '.', '?', 'a', 'b', 'c',
        'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
        'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
        't', 'u', 'v', 'w', 'x', 'y', 'z', '0',
        '1', '2', '3', '4']`

Is it a right option?

**Comment by Slyne** [comment]
It looks like pinyin with tone (0, 1, 2, 3, 4) added, one way to represent the pronunication for Chinese characters.

**Comment by ican24** [comment]
So may I use same (0, 1, 2, 3, 4) for my none English language (Armenian)?

Currently my lables look like
`labels: [' ', '!', '"', "'", '(', ')', ',', '-', '.', ':', ';', '?', '՜', '՞',
         'Ա', 'Բ', 'Գ', 'Դ', 'Ե', 'Զ', 'Է', 'Ը', 'Թ', 'Ժ', 'Ի', 'Լ', 'Խ', 'Ծ', 
         'Կ', 'Հ', 'Ձ', 'Ղ', 'Ճ', 'Մ', 'Յ', 'Ն', 'Շ', 'Ո', 'Չ', 'Պ', 'Ջ', 'Ռ', 
         'Ս', 'Վ', 'Տ', 'Ր', 'Ց', 'Ւ', 'Փ', 'Ք', 'Օ', 'Ֆ', 'ա', 'բ', 'գ', 'դ', 
         'ե', 'զ', 'է', 'ը', 'թ', 'ժ', 'ի', 'լ', 'խ', 'ծ', 'կ', 'հ', 'ձ', 'ղ', 
         'ճ', 'մ', 'յ', 'ն', 'շ', 'ո', 'չ', 'պ', 'ջ', 'ռ', 'ս', 'վ', 'տ', 'ր', 
         'ց', 'ւ', 'փ', 'ք', 'օ', 'ֆ', 'և'] `

**Comment by Slyne** [comment]
I think if your labels can cover the all the characters which appear in the training dataset, then it is ok.. You don't need to add the tone symbols (which seems only appear in Chinese)
![image](https://user-images.githubusercontent.com/6286804/70501891-4eb96180-1b5a-11ea-84b7-c04f94748993.png)
Reference:
https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_charthttps://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart

**Comment by ican24** [comment]
Thank you very much!
You support is very quick and effective.

**Comment by MuyangDu** [comment]
@ican24 Hi, The input to the Tacotron2 should in some way contain the pronunciation information in your language. For example, we use 'pinyin' to represent the pronunciation of a Chinese character.  For a Chinese character '好', its 'pinyin' is 'hao3'. For a Chinese phrase '你好', its 'pinyin' is 'ni3 hao3'.  
There are tens of thousands of different Chinese characters. If we simply use the Chinese characters as input. There will be tens of thousands of labels and it will be so hard for the model to learn. Instead, we use the pinyin as input so the input labels are just 26 English characters + 5 tones (0-4) + some symbols. Which should make Tacotron2 easier to learn.
So In your case. Since there are only 38 characters in Armenian. You can try directly using the characters of Armenian as input(label).

**Comment by ican24** [comment]
Dear Muyang Du, 
Thank you for your detailed explication and confirmation!
Any detail is so important before launching long term processes like tacotron2.py and waveglow.
