### ISSUE TITLE
how to convert .pt models  into .nemo format[Question]

### ISSUE THREAD

**Issue by Ashbajawed** [NVIDIA/NeMo#2070]
I have following  blog [Jump-start Training for Speech Recognition Models in Different Languages with NVIDIA NeMo](https://developer.nvidia.com/blog/jump-start-training-for-speech-recognition-models-with-nemo/#respond) and successfully finetune the model on my custom data. Now I have to test the models but in checkpoint directory I have  3 .pt files as output (JasperDecoderForCTC-STEP-80000.pt   JasperEncoder-STEP-80000.pt  trainer-STEP-80000.pt)

I am confuse how would I convert them into .nemo format or is there any other way to use those models for inference.

code : [quartznet.py](https://nemo-public.s3.us-east-2.amazonaws.com/transfer-learning-04-2020/quartznet.py)
nemo version = 0.11

Also it will be helpful if anyone can share tutorial for finetuning on latest release

**Comment by ericharper** [comment]
We have completely changed NeMo since .11. We highly recommend to start using our latest stable version. Please see our User Guide: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/ and our Tutorials: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/tutorials.html for how to get started with NeMo.
