### ISSUE TITLE
No pad_token,eos_token,sep_token,cls_token in SentencePieceTokenizer

### ISSUE THREAD

**Issue by songtaoshi** [NVIDIA/NeMo#2404]
https://github.com/NVIDIA/NeMo/blob/70987d1c09776550304d76d3651f1e41ffe90a84/nemo/collections/common/tokenizers/sentencepiece_tokenizer.py#L191.   

Hi I find actually no pad_token,eos_token,sep_token,cls_token in SentencePieceTokenizer's property.

**Comment by songtaoshi** [comment]
@junkin @ranman @aaronp24 @ttyio

**Comment by titu1994** [comment]
Sentencepiece tokekizer requires these tokens to be built into the SPE model itself during construction time. Till now, there was no need of the above tokens in ASR and NLP models generally use Hugging face WordPiece Tokenizers. 

We now have added flags to add bos, eos and pad tokens during construction time if required - 
https://github.com/NVIDIA/NeMo/blob/r1.1.0/scripts/tokenizers/process_asr_text_tokenizer.py#L109

**Comment by titu1994** [comment]
Cls and sep tokens are not supported as Sentencepiece isn't yet we'll supported for NLP models

**Comment by songtaoshi** [comment]
> Sentencepiece tokekizer requires these tokens to be built into the SPE model itself during construction time. Till now, there was no need of the above tokens in ASR and NLP models generally use Hugging face WordPiece Tokenizers.
> 
> We now have added flags to add bos, eos and pad tokens during construction time if required -
> https://github.com/NVIDIA/NeMo/blob/r1.1.0/scripts/tokenizers/process_asr_text_tokenizer.py#L109

But actually the spe tokenizer initialize with legacy=True, And it would query with self.pad_token.   **But the self.pad_token is not constructed.**  

https://github.com/NVIDIA/NeMo/blob/70987d1c09776550304d76d3651f1e41ffe90a84/nemo/collections/asr/parts/mixins/mixins.py#L84

https://github.com/NVIDIA/NeMo/blob/10ddab6ff48a5afb389a57604bff6c6681b3257f/nemo/collections/common/tokenizers/sentencepiece_tokenizer.py


```python  
    @property
    def pad_id(self):
        if self.legacy:
            pad_id = self.tokens_to_ids([self.pad_token])[0]
        else:
            pad_id = self.tokenizer.pad_id()
        return pad_id

    @property
```


And also I am a little confused there is no need for sos_token/eos_token for RNNT training ?  

BTW, is there any tutorial about how to train RNNT-BPE model with steps in details and also the data format.  
e.g.     
       1. train a tokenizer with what kind of data, the data example  (English & Mandarin)
       2. the cmd to train the model

**Comment by songtaoshi** [comment]
@titu1994

**Comment by titu1994** [comment]
RNNT model notebooks are not available yet because we have not released any checkpoints for RNNT yet. It is under active development but might take a month or two. 

We have tried RNNT training with and without bos/eos and they train just fine either way. Difference in WER is negligible. 

We will consider disabling legacy mode in a few releases. It's causing more confusion than necessary.

**Comment by songtaoshi** [comment]
Could you share any script training RNNTBPE successfully, maybe I do not need the jupyter in detail.   
And by the way, what is the RNNT WER in which dataset ?

**Comment by songtaoshi** [comment]
@songtaoshi

**Comment by songtaoshi** [comment]
And also I find lots of problems caused by the hard code in the tokenizer while the BPE tokenizer model can be created by the users. So the inconsistency truly wastes lots of time for the user.    Such as the  
https://github.com/NVIDIA/NeMo/blob/5fcfa9e7bf2da39d622071fc0cac592f993f89ea/nemo/collections/asr/parts/mixins/mixins.py#L105.   While the user could create the unk to the vocab outside

**Comment by titu1994** [comment]
UNK is set by default in the Sentencepiece tokekizer - the tokenizer script provides no override for it. We don't expect users to have custom SPE Tokenizers built without the script since there can be too many inconsistencies between model outputs then. 

RNNT training scripts are available already in the examples directory, though the encoders for related models must be updated to include confirmed or citrinet - by default it's a toy model meant for AN4.
