### ISSUE TITLE
Run Offline_ASR (python notebook) decode with a GPU

### ISSUE THREAD

**Issue by Iagodel** [NVIDIA/NeMo#2413]
Hello,

I'm using the Offline_ASR notebook testing some large and small values for width, alpha and beta in 'beamsearch', all is correct and returning good results, but needs so much time to return those results. This script is running in Colab.
Have some way to run this notebook or only the beamsearch part with a GPU, or just accelerate in general?

**Comment by titu1994** [comment]
The beam search library we use is CPU only, therefore for now there is no way to improve speed by using GPU.

**Comment by DiegoJota** [comment]
Hi,

Is there another way to use the language model using GPU?

**Comment by VahidooX** [comment]
The grid search for N-gram LM should not take that long and its something you need to do it once for each model to find the best values. Have you tried this script: 
https://github.com/NVIDIA/NeMo/blob/stable/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py

You may use neural rescorer LM instead of (or in combination with) N-gram LM which uses GPU as it is a neural network:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html#neural-rescoring

But beam search decoding is needed anyway to use neural rescorer, so I guess it is not going to help your case.

**Comment by ridasaleem0** [comment]
Hi,
Is there a way that we can run the Offline_asr notebook with microphone instead of audio file?

like the one online_ASR_Microphone_demo notebook?

**Comment by titu1994** [comment]
No it's not possible yet as we depend on a library which works only on the CPU.

**Comment by ridasaleem0** [comment]
> No it's not possible yet as we depend on a library which works only on the CPU.

@titu1994 so we cannot use offline asr with microphone instead of transcribe() function which takes in an audio file?

**Comment by titu1994** [comment]
No, you'll have to write your own data loader for microphone as done in notebook 2

**Comment by Iagodel** [comment]
Hello guys, I have being a trouble with eval_neural_rescorer. I don't know if I doing wrong or forgetting something,
When I running the script with lm_model_file, beam_file eval_manifest and beam_size, I got this error:

AttributeError: 'ConvASREncoder' object has no attribute '_embedding'

Someone knows about this error and can help me? I tried to search something but without success

**Comment by VahidooX** [comment]
It looks like you are passing an ASR model as lm_model while this should be a LM neural network like Transformer:
https://ngc.nvidia.com/catalog/models/nvidia:nemo:asrlm_en_transformer_large_ls
