### ISSUE TITLE
Question: How to speed up training?

### ISSUE THREAD

**Issue by naymaraq** [NVIDIA/NeMo#2593]
Hi
I have a question about fast training.

I am trying to train QuartzNet15x5 from scratch on 6000 hours of data with 2xA100 GPUs. It takes 10 hours per epoch.

How can I speed up the training or convergence speed? 

I am using
2xA100 with 40GB RAM
mixed precision
80 num workers in torch loader

what else can i do to speed up the training?

**Comment by titu1994** [comment]
For that much data, there's not much to be done other than scaling to more GPUs. Hopefully you are already using AMP and batch size 32. 80 workers is excessive, we get by with 32 or even 16 workers but if the machine isn't showing perf degredation then 80 is fine too. Audio duration should not exceed 17 seconds so that larger batch size can be used. 

You can also try training faster models like Citrinet 384 (21 M params) or Conformer Medium (30 M params) which have larger strides so they train faster than QuartzNet.

**Comment by naymaraq** [comment]
Thanks @titu1994

**Comment by chrjxj** [comment]
@naymaraq  since you have A100 with TF32 format as default in training, does mixed precision offer speerdup in the training?

**Comment by naymaraq** [comment]
> @naymaraq since you have A100 with TF32 format as default in training, does mixed precision offer speerdup in the training?

I didn't run without mixed precision:)
