### ISSUE TITLE
bug in get_hi-mia_data.py

### ISSUE THREAD

**Issue by ali2iptoki** [NVIDIA/NeMo#2630]
In the script of downloading `get_hi-mia_data.py` there is a small bug. I think line  `l.output.write_wav(line, y, sr)` in `__process_data ` needs to be changed by `sf.write(line, data=y, samplerate=sr)`.
By the way when we run this script we will get three folders:

1. dev
> dev.jason including : 16464 samples, dev_all.json: 164640 samples and train.json: 148176 samples

2. test
> test_all.sjon uncluding 165120 samples. When you check the number of labels we will find 13620 labels. How that? How they are related to speakers, or more precisely to 44 speakers?
3. train
> dev with 99309 samples, train: 893774 and train_all:993083 samples

To the best of my knowledge, the number of speakers in dev is 42, in test 44 and in train in 254 (correct me if  I am wrong, please) and each speaker records 160 discours. So, for example, 42*160 != 164640. or you mean the sum of the 160 for each speaker are decomposed, and the sum of discours for all the speakers =  164640.

Indeed, which one of dev, test, train can we use for just train a model and generate the labels for speaker identification.? can I use only dev since it containes dev.json, train.json and the sum of their samples is 16464+148176=164640 samples?

**Comment by nithinraok** [comment]
Thanks for finding the bug, looks like librosa deprecated the function. Can you submit a PR to fix it? 

Regarding the dataset, not sure about the statistics on the number of samples per speaker. In dev set AFAIK there are probably 3920 samples per speaker. (42x3920 = 164640) and for the train set it's not fixed but the average number of utterances per speaker is 3909.776. (254*3909.776 = 993083). 

For speakernet training, The files we need are train_manifest.json and dev_manifest.json. (The dev, test, and train are part of hi-mia dataset we don't have control over that and their set names are different from our dev and train manifest files analogy). If you observed `get_hi-mia_data.py` script, it created dev and train manifest files under hi-mia dev and hi-mia train folders (10% of data). Combine dev manifest from both sets as single dev_manifest.json and similarly combine train manifests from dev and train to create a single top-level train_manifest.json. Use those to train and validate speakernet. The test set is not used during training, it's only used to extract embeddings and perform speaker verification to get Equal Error Rate numbers (EER) if you use their trial file for HI-MIA competition (we don't provide any script to calculate EER for HI-MIA). 


The numbers reported in [Paper](https://arxiv.org/abs/2010.12653) were not trained using HI-MIA, but voxceleb datasets. Since there are so many datasets in the wild, its not a good idea to create a script for each of them, and due to open-source availability of hi-mia dataset, I used it to demonstrate on how one can generate similar manifest files for training and validation. For any other datasets see section `All-other Datasets` at https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/speaker_recognition/datasets.html#all-other-datasets.

**Comment by ali2iptoki** [comment]
@nithinraok Thanks for your reply. What do you mean by PR? and I think there is another scenario for the dev and train folder. Instead to combine them, we can train speakerNet using the dev.json and train.json in train folder and then fintune this model on the dev.json and train.json in dev folder. In both cases, we do a speaker identification.

My only concern still about speaker verification. How can the model generates embedding for data (of test folder) not seen in the training. Correct me please: we use the test_all.json to generate embedding using your provided extract embedding script.  and then based on gold standard file which should includes the correct answers. did you know where can find such as file?
Thanks again
