### ISSUE TITLE
FileNotFound loading fine tuned stt_en_citrinet_512 model

### ISSUE THREAD

**Issue by peterhanlon** [NVIDIA/NeMo#2660]
**Describe the bug**

If I attempt to fine tune stt_en_citrinet_512, the training runs as expected but when I subsequently try to load a checkpoint I get the following error

FileNotFoundError: src path does not exist or it is not a path in nemo file. src value I got was: /home/smajumdar/PycharmProjects/nemo-eval/nemo_beta_eval/asrset/manifests/asrset_1.4/tokenizers/no_appen/tokenizer_spe_unigram_v1024/tokenizer.model. Absolute: /home/smajumdar/PycharmProjects/nemo-eval/nemo_beta_eval/asrset/manifests/asrset_1.4/tokenizers/no_appen/tokenizer_spe_unigram_v1024/tokenizer.model

I can see that the path is the tokenizer path from the original stt_en_citrinet_512 model, however, I don't understand why it's trying to load the file when I load the checkpoint.

**Expected behavior**

The checkpoint file should load without throwing a FileNotFound error

**Environment overview (please complete the following information)**

AWS Sagemaker
ml.g4dn.xlarge
%pip install nemo_toolkit['all']==1.2.0

Otherwise, please provide:
- OS version: Debian GNU/Linux 10 (buster)
- PyTorch version : 1.9.0+cu102
- Python version : 3 .6.13

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
This is odd, when you say you try to restore the checkpoint do you mean you call EncDecCTCModelBPE.restore_from("xyz_new.nemo") and it fails? 

Pytorch lightning intermediate checkpoints will face this issue, but not Nemo models.

**Comment by titu1994** [comment]
The tokekizer is a part of the model, the only way to properly restore the model is to restore it from a serialized .nemo file instead of a ckpt file that pytorch lightning generates during training. We recommend using experiment manager with the "always_save_nemo" flag to save intermediate Nemo files during training.

**Comment by peterhanlon** [comment]
Thanks for responding so quickly! I'm loading the checkpoint using the following

base_model = nemo_asr.models.EncDecCTCModelBPE.load_from_checkpoint(checkpoint_path='/root/asr16000/models/last.ckpt')

**Comment by peterhanlon** [comment]
I'm using the following callback in the Training. Do you have an example with experiment manager?

from pytorch_lightning.callbacks import ModelCheckpoint
                
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',
    dirpath='/root/asr16000/models/',
    filename='moneypenny-asr-{epoch:02d}-{val_loss:.2f}',
    period=1,
    save_last=True
)

**Comment by titu1994** [comment]
Yes as mentioned - that's the reason you are facing the issue. The pytorch lightning checkpoint (.ckpt) cannot be restored properly (you can load it with torch.load and see that it's config points to the incorrect tokenizer path), only .Nemo files can restore properly, which correctly restore the tokenizer for the model from within the .Nemo file itself. What you can do however quite easily is 

1) untar the original Nemo file to get the tokenizer

2) create a new model pointing to this tokenizer 

3) load the pytorch lightning checkpoint and manually load the state dict into this new model

4) save the model with save_to() in order to preserve a new .Nemo file. 

I would suggest to just use exp manager to train again and save a Nemo checkpoint always

**Comment by peterhanlon** [comment]
Thanks I've added the exp manager and the nemo checkpoints are being saved now. Thanks!
