### ISSUE TITLE
Pass manifest to ClusteringDiarizer

### ISSUE THREAD

**Issue by roman-vygon** [NVIDIA/NeMo#2722]
**Is your feature request related to a problem? Please describe.**

Clustering diarizer class accepts paths to audiofiles instead of a manifest as all other models, however it still converts it to a NeMo-like manifest inside path2audio_files_to_manifest function. 

**Describe the solution you'd like**

An option to provide a manifest instead of a list of paths, e.g.
```python
assert paths2audio_files is not None or manifest_path is not None
if manifest_path is None:
   manifest = path2audio_files_to_manifest(paths2audio_files)    
```

**Comment by nithinraok** [comment]
Thanks for the question, we did that on purpose. 

we wanted to provide a simple way to diarize for single files using a single liner as:
`sd_model.diarize(<path2_audio_file>)` and also we use it to map ground truth rttms for calculating DERs.

Since providing ground truth rttms as a list of files and audio_files as manifest, didn't feel right to us when evaluating DERs but for inference, only audio files would be used (which can be manifest). This is a valid feature request, I will ponder on this to align with the rest of the Nemo models, for the next release.
