### ISSUE TITLE
ASR: Support for custom words/vocabulary

### ISSUE THREAD

**Issue by sunilpro** [NVIDIA/NeMo#278]
Is there a way to add custom words likes proper names or city names, etc without retraining the released QuartzNet models on the fly (like for each user who has his own set of contact names)?
I followed this article:
https://devblogs.nvidia.com/how-to-build-domain-specific-automatic-speech-recognition-models-on-gpus/
But apparently this needs new audio dataset and retraining

**Comment by blisc** [comment]
NeMo QuartzNet is trained on characters. So long as your custom words are comprised of English characters, there is no need to add custom words as it should work out of the box.
It would be beneficial to fine-tune QuartzNet models with in-domain speech if you have the speech data available.

If you want to improve the recognition of custom words, you could further create your own n-gram language model (which operates on the word level) to boost the probability of certain words. In order to create your own language model, you would need only the in-domain transcripts, the audio file is not necessary for this step.

**Comment by sunilpro** [comment]
@blisc That'd be amazing if it works reliably. I'll try and post my findings here. Thanks!

**Comment by ShantanuNair** [comment]
@blisc curious if other language models other than n-gram would work here. Would BERT be a suitable language model "type"? I'd figure it might be suitable for the task since it was trained using masked tokens and that the context would help quartzite choose an appropriate transcription.

**Comment by kruthikakr** [comment]
> @blisc That'd be amazing if it works reliably. I'll try and post my findings here. Thanks!

Hi..Any inputs on this to try ?  I need to add some custom words , how to add the custom LM for citrinet model ?
