### ISSUE TITLE
CUDA error: an illegal memory access was encountered while training MatchboxNet (Numba CUDA)

### ISSUE THREAD

**Issue by dmitrytyrin** [NVIDIA/NeMo#2916]
Hello!
I train MatchboxNet model with custom labels and standard config file.
If I use batch_size (train, test, validation) = 512 I consume 3Gb of GPU memory (Tesla V100) and everything works fine. 
If I increase batch_size to 1024 I get ```RuntimeError: CUDA error: an illegal memory access was encountered``` at the first step. 
Running script with ```CUDA_LAUNCH_BLOCKING=1``` gives next output:
```numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuLaunchKernel results in UNKNOWN_CUDA_ERROR```
Tried different torch versions - no results.

Any ideas how to fix this?

Numba version: 0.54.0
Python: 3.7.9
CUDA version: 11.1
Driver Version: 455.32.00

**Comment by titu1994** [comment]
Probably just running out of GPU memory.

**Comment by dmitrytyrin** [comment]
@titu1994, I have 32 Gb available on my GPU. Batch size 512 consume 3 Gb and 1024 batch should fit memory.
Running out of GPU memory gives OOM cuda error, but I have an illegal memory access.
Can be problem with numba/cuda synchronize or some hardcoded shapes in code?

**Comment by titu1994** [comment]
Oh I missed the Numba there. Can you post the full stack trace ? What is the version of cuda, pytorch, and Numba installed in the system ? 

Also can you try providing this argument as false in the config to see if model can train when spec augment numba is disabled ? https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/modules/audio_preprocessing.py#L459 - if it can, then it's a bug in the kernel and Ill change the default until the bug is fixed, though it will slow down training a bit. 

Also, to replicate on my side, can you detail what dataset is being used ? I did try less than 256 batch size for ASR but not batch size 512 and above for MatchboxNet, might be a bug in how numba kernel is launched for such large batch sizes.

**Comment by dmitrytyrin** [comment]
Disabling spec augment numba helped! So it is definitely a numba bug with large batch sizes.
With this flag disabled I can launch training with 8192 batch size (25 Gb utilization).
By the way, how long have you trained english MatchboxNet model? What batch sizes, how many GPUs, epochs, lr and etc.?

**Comment by titu1994** [comment]
Good catch, fixed the issue when batch size is larger than the max thread buffer in https://github.com/NVIDIA/NeMo/pull/2924
