### ISSUE TITLE
AttributeError: module 'nemo.collections' has no attribute 'nlp'

### ISSUE THREAD

**Issue by MuhammedTech** [NVIDIA/NeMo#2966]
I am getting the 
`AttributeError: module 'nemo.collections' has no attribute 'nlp'
`
I am on the latest version of nemo, and also, `nemo.collections.asr` or `nemo.collections.cv` works perfectly

**Comment by ibrahimab** [comment]
You only have to install the toolkit, then run `import nemo.collections.nlp.models` and it will happen. I have narrowed it down to the experimental `nemo.collections.nlp.models.duplex_text_normalization` package that seems to be causing the problem. If you go in to `nemo/collections/nlp/models/__init__.py` and comment out the following:

```python
from nemo.collections.nlp.models.duplex_text_normalization import (
    DuplexDecoderModel,
    DuplexTaggerModel,
    DuplexTextNormalizationModel,
)
```
the import will succeed

**Comment by ibrahimab** [comment]
My guess is that it works for you because you have tested it on google colab or your own amd64 based hardware, but this problem only arises on arm64 based systems, like the nvidia jetson nano on which I have tested and isolated the problem.

The nemo containers are based on amd64, yet the jetson nano is arm based, so people need to use one of the l4t images, like [lf4-ml](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-ml/tags).

That is why I haven't provided a google colab notebook as that would make no sense and would run the notebook on amd64 based runtime, unless I'm missing something and I can create a notebook based on arm64? I would love to hear input on this.

But even then your suggestion on running it on nvcr.io/nvidia/nemo:1.4.0 wouldn't work as it is not multiarch and will not run on jetson nano.

Using jetson nano, running container l4t-ml, installing nemo_toolkit[all] will succeed (though you have to do a lot of manual modifications to make things work properly, but im working on a simplified dockerfile for easy use on jetson nano), but once you've got nemo_toolkit installed, you will still fail importing nlp unless you comment out the lines I quoted [here](https://github.com/NVIDIA/NeMo/issues/2966#issuecomment-944857599).

For people that just wanna toy around with nemo without all this hassle and just wanna quickstart on jetson nano, I would suggest using the following repo by @dusty-nv to get up and running: https://github.com/dusty-nv/jetson-voice 

So instead of a colab notebook, I've prepared a simple video that shows the problem.

https://user-images.githubusercontent.com/26875/138000560-ac399b15-a27b-4d82-9bfa-2a013cfc90df.mov

**Comment by ibrahimab** [comment]
@blisc @okuchaiev any updates?

**Comment by dexception** [comment]
This is the problem with Nvidia. They never provide support. 
What a bunch of arrogant sob.

**Comment by okuchaiev** [comment]
NeMo is toolkit for *training and fine-tuning* which is why we don't officially it on platforms like Jetson. 
Some features may or may not work there, but this is not our focus as we don't see training use-cases there.
