### ISSUE TITLE
Training never finished

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2987]
Hi,

My last workouts never end correctly, he gets stuck at this stage:
![Image](https://user-images.githubusercontent.com/49459897/136842870-f279377b-cb4e-40e4-938f-e44f5d6dd417.png)
If I force a ctrl+c it ends, but I'm afraid to kill some processing. I leave it for hours and this stage is never changed. Any suggestions for this issue? Or is it something normal?

Environment: 
JupyterLab
NeMo 1.3.0 (Previous also have the same problem)
GPUs: 3
Python: 3.8
OS: Ubuntu

**Comment by VahidooX** [comment]
Is the max_epoch=255?
Which script do you use?

**Comment by DiegoJota** [comment]
max_epoch=256
I am using this sctipt (Character Encoding CTC Model)
https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb#scrollTo=FnmVqx8aegwR

**Comment by titu1994** [comment]
Sometimes notebook env + DDP can hang due to various reasons. You were presumably trying to save the best Nemo checkpoint under DDP using exp manager which might have locked during file reading or writing. 

If control c moves past that, and then next cell allows save_to (or if .Nemo checkpoints already exist) then there is no issue and control c can be safely used
