### ISSUE TITLE
Using wordpiece for ASR

### ISSUE THREAD

**Issue by cri5Castro** [NVIDIA/NeMo#314]
hello i'm trying to train a quartz model using nemo, but i wanted to know if is posible to use wordpiece based prediction instead of complete words, i was thinking of just preprocessing the transcrips with a wordpiece tokenizer and input them into de model

**Comment by okuchaiev** [comment]
This means you will need to switch from char-based model (currently Jasper and QuartzNet are char-based for English) to a BPE token-based model. Thus, you vocabulary would effectively increase from <30 characters to several thousands BPE tokens. 
This is certainly possible, because we already have trained QuartzNet on Mandarin (which effectively has thousands symbols instead of <30). However, we haven't released any BPE - based model for English. But we plan to do so sometime.

**Comment by cri5Castro** [comment]
thanks for the reply , I wonder if is suitable to train with CTC loss with such large label space (thousands) , have you train the mandarin model using CTC?

**Comment by okuchaiev** [comment]
yes, Mandarin models were trained with CTC loss

**Comment by cri5Castro** [comment]
hello , also do you . know if  the lm should be char level or word level?

**Comment by Slyne** [comment]
@cri5Castro If you use the mandarin model, you may build a char level language model. The decoder will detect if the language model is char level, it will call the score function whenever it meets with a character. If the language model is word level, it will call the score function when it meets with a space in the transcript.   It only depends on the modelling units. For example, in some cases, we may use word piece/sent piece for mandarin corpus and in such cases, you may use word piece built language model.
