### ISSUE TITLE
Support TPU Training

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3240]
Hi,
Thanks for your great repo. I think it would be really great if Nemo support TPU training (due to the fact that training on some large datasets on GPU is slow, and TPU will probably help in these scenarios. In addition, other speech frameworks, to the best of my knowledge, such as SpeechBrain, ESPNet, etc., currently do not support TPU training, so in this viewpoint, it would be a great benefit for Nemo).
Best

**Comment by titu1994** [comment]
That wont be possible for the vast majority of Nemo models. The tpu is unable to handle dynamic models with dynamic shaped inputs (which is practically all of ASR TTS models). 

It's not supported on most ASR frameworks because it's not feasible to do so for anything but the most trivial architecture and padded fixed inputs.

**Comment by ahkarami** [comment]
@titu1994 
Thank you very much for your very good guidance. I understand the main issue for TPU training. 
Best
