### ISSUE TITLE
Warning about slow loading of non-wav formats

### ISSUE THREAD

**Issue by roman-vygon** [NVIDIA/NeMo#3336]
**Is your feature request related to a problem? Please describe.**

Recently I've tried to understand why is my gpu usage spiking from 0 to 100% and why does training seem to halt every num_workers batches. What I found is that my dataset consisted of .opus and .mp3 files, and that they load 2-30 times slower than those same files when converted to .wav.

**Describe the solution you'd like**

A warning message that informs the user that non-wav files might become a bottleneck for training.

It seems wrong to show this message in segment.py cause it would be displayed for each of those files and pollute the logs.
Maybe the ManifestProcessor can keep a list of found formats and in the end of processing compare it to soundfile.available_formats()?

**Comment by titu1994** [comment]
Instead of putting this in the code, i'd rather document it in the ASR and TTS documentation pages for datasets. This is expected, wav wastes a lot of space but is the fastest to decode.

**Comment by AndreyYashkin** [comment]
I have recently met the similar issue with my opus dataset. After investigating profiler logs I could noticeably speed up loading data by hacking NeMo to use `resample` method from torchaudio instead of a much more slower librosa implementation (you can find resampling benchmarks in pyotrch docs), but it did not solved the problem completely.

**Comment by titu1994** [comment]
Interesting, on our testing, Torchaudio resampling is slower than soundfile for audio loading while torchaudio is better for resampling. Since we suggest to users to resample ahead of time instead of on the fly, we stick to soundfile + librosa combo since Torchaudio is an optional dependency. 

Y
The performance hit you are seeing us due to decoding, nothing beats wav for speed but it wastes storage space.
