### ISSUE TITLE
ASR transcribe_speech with Language Model

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3414]
Hi, 
I have 2 questions about ASR Language Modeling:
1- Is there any implemented code in Nemo, for generating the json file of the predictions of an ASR model with a N-gram LM? Something like the [transcribe_speech_parallel.py](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/transcribe_speech_parallel.py) code. I know that, I can easily implement this code via [Offline_ASR.ipynb Tutorial](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/Offline_ASR.ipynb#scrollTo=nV1CAy0Dit-g). But I want to know if such a code is already available in the framework?
2- Would you please kindly describe what is the `Oracle WER/CER` mean when using the [eval_beamsearch_ngram.py](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py) code? 
Best

**Comment by titu1994** [comment]
(1) - we do have scripts available to perform beam search. Please refer to asr documentation. https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html
(2) - Oracle WER is the lowest possible WER that could have been obtained with the given acoustic model, if there existed a perfect language model. Since no LM is perfect, Oracle WER is to understand the capability of the model rather than use as actual score.

**Comment by ahkarami** [comment]
@titu1994 
Thank you for your answers.
For the first question, I am familiar with the [eval_beamsearch_ngram.py](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py) code, however this code doesn't produce a json output file as a manifest format which one can use it as the input of the Speech Data Explorer (SDE) tool. I mean that, is there any code in Nemo, that can produce such json file via an ASR model + N-gram LM to analyze its results via SDE tool?
Best

**Comment by titu1994** [comment]
The output of that script is pretty simple, you could write a simple script to create a JSON file from that. There doesn't exist a pre written script for that

**Comment by ahkarami** [comment]
Thank you very much. You are right.
