### ISSUE TITLE
Reached max decoder steps

### ISSUE THREAD

**Issue by davidmartinrius** [NVIDIA/NeMo#3661]
Hello,

I'm training a model on Tacotron2. I tried little datasets, large datasets, but always I get the same messages.

Reached max decoder steps XXXX

By default there are 1000 steps. I tried the default configuration and also I tried greater values.

I thought it was caused because the labels property in tacotron2.yaml. But I grouped all the letters in my dataset and every letter is on the "labels" property.

Also I tried adding a dot at the end of each sentence. Absolutely all of the sentences are between 1 and 10 seconds.

The dataset is all in spanish. I tried to train minutes, hours, etc. I mean in the json file I tried from 10000 registers to 100 registers.

When training it always notice Reached max decoder steps XXXX

Do you know why is it happening? Do you know how to solve it?

Thank you!

**Comment by davidmartinrius** [comment]
Hello, I would like to find a solution for this. I am still happening this issue. 

Do you know why is it happening? 

I think it would be great a complete NeMo training tutorial. 

Currently I am working in a trial and error, an it is very complicated to work like this.

If already exists a complete tutorial I still not found it. I know there is a folder in https://github.com/NVIDIA/NeMo/tree/main/tutorials and https://github.com/NVIDIA/NeMo/tree/main/examples

Unfortunately, for me it is too limited as I have little experience in this project. For new coming people it is complicated to start a project with NeMo.

Thank you,

David

**Comment by blisc** [comment]
We strongly recommend you start with the FastPitch or TalkNet model.

Tacotron2 is a poor model to start with because you will struggle to train the attention module. Most of the academic community has moved on from tacotron2 due to issues with attention. You can see #282, #596, and #2352 for more Tacotron2 discussion.

You can mitigate the attention issues by adding a attention guidance loss as in https://arxiv.org/abs/2108.10447. There are no current plans to add this feature to NeMo Tacotron2.
