### ISSUE TITLE
get_statistics_with_mask (mean vs sum)

### ISSUE THREAD

**Issue by makcedward** [NVIDIA/NeMo#3827]
Thank you for providing a very good framework and solution for speaker recognition.

To understand more about it, I read through source code and paper. I want to clarify one of the calculation in `get_statistics_with_mask`. To calculate statistics, the variable name and description is `mean` while the implementation is `sum`  when calculating input and mask.

May I confirm whether it is `mean` or `sum` operation? 

https://github.com/NVIDIA/NeMo/blob/v1.7.0/nemo/collections/asr/parts/submodules/tdnn_attention.py#L87

**Comment by nithinraok** [comment]
Thank you for your interest @makcedward 

It returns the sum of `m * x`  when mask `m = 1/N` where N is the number of values in `x` then the resulting value would be mean. 

In other cases, with sum of `m * x` then we can selectively mask only values where it is required, at this [location](https://github.com/NVIDIA/NeMo/blob/256236f684cd08abd27008d6a9c41d77993be138/nemo/collections/asr/parts/submodules/tdnn_attention.py#L266) we calculate mask and use it to calculate mean (since we devide mask by num of values) and standard deviation.

**Comment by makcedward** [comment]
thank you for the clarification
