### ISSUE TITLE
TTS FastPitch_Finetuning Tutorial is not runnable

### ISSUE THREAD

**Issue by chychen** [NVIDIA/NeMo#3895]
https://github.com/NVIDIA/NeMo/blob/stable/tutorials/tts/FastPitch_Finetuning.ipynb 

this is an untested code, which is
unrunnable due to wrongly mixing code and text, missing a few lines of codes ... etc.

**Comment by redoctopus** [comment]
As mentioned in the tutorial, that section does not have runnable training due to resource limitations on Colab, and the code was originally deliberately non-runnable since there is no following training command.

I've updated the notebook in #3954 to try to make this clearer, and moved that section to a code block for anyone who might want to play around with it locally.
