### ISSUE TITLE
Speaker Diarization: Known Number of Speakers

### ISSUE THREAD

**Issue by naymaraq** [NVIDIA/NeMo#4234]
Hello NeMo team

I evaluated NeMo clustering diarizer on VoxConverse dataset. And the results are wonderful. But when I am providing the actual number of speakers through manifest, results get worse. I noticed the same behavior for NIST SRE 2000 dataset too. I am wondering why is this happening? Is it something related to dataset (like overlap speech)?

<img width="873" alt="Screen Shot 2022-05-23 at 23 07 41" src="https://user-images.githubusercontent.com/47416614/169889294-ff7b4100-5f9c-4b58-b695-06a686c34c52.png">

**Comment by nithinraok** [comment]
Is it possible for you to share the numbers on VoxConverse? 

It happens when a speaker(s) speaks for very few seconds compared to other speakers in an audio file. When the number of speakers is provided, NMESC clustering method tries to cluster the embeddings with the provided number of speakers, and since there are very few embeddings, there is less chance of grouping them accurately. 

In another case when the number of speakers is not provided, clustering method assigns those few samples to other speakers leading to very few diarization error rates (DER).

**Comment by naymaraq** [comment]
Let me share the results.
On VoxConverse Dev set, I obtained 3.3% DER with Oracle VAD and with unknown #speakers. And 6-7% DER with oracle VAD and known #speakers.

**Comment by nithinraok** [comment]
Thanks for sharing the results, they look great.
