### ISSUE TITLE
OSError: libtorch_hip.so: cannot open shared object file in Speaker_Diarization_Inference

### ISSUE THREAD

**Issue by AMITKESARI2000** [NVIDIA/NeMo#4513]
Followed the steps here : https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb
to run in jupyter notebook and just ran the whole notebook as it is. But got the error `OSError: libtorch_hip.so: cannot open shared object file: No such file or directory` when importing `nemo.collections.asr.models`

**Environment details**
![image](https://user-images.githubusercontent.com/66141447/177719440-0e6a7cbe-4266-4f69-ae8c-01ebb527b50d.png)

- OS version Ubuntu 20.04
- PyTorch version 1.11.0
- Python version 3.9.12

**Comment by tango4j** [comment]
@AMITKESARI2000 Can you specify the steps where you get the error in the  [Speaker_Diarization_Inference.ipynb](https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb) notebook?

**Comment by tango4j** [comment]
@AMITKESARI2000  Thanks for checking it again. Since we always make sure main or the latest release to run without bug free, we cannot make sure the code is bug-free with the past versions of requirements. Having said that, this error is originating from pytorch version where they recently updated libtorch related libraries. If you happen to see such issues with the old version of NeMo of pytorch, remove( or comment out) all `@torch.jit.script` decorators in (nmesc_clustering.py)[https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/utils/nmesc_clustering.py] code.
