### ISSUE TITLE
nemo_asr - question about memory consumption in quartznet

### ISSUE THREAD

**Issue by kwasnydam** [NVIDIA/NeMo#482]
Hello Everybody.

I have recently ran into some Out of Memory problems and I am currently trying to understand what does the memory consumption of the quartznet scale with exactly. I am trying to run the training for the 5x3 variant of quartznet on some polish language corpora. What I would like to know is the scaling of memory consumption with the following factors:
1. Length of input audio - the filters will have to pass through longer sequence, so that would extend graph of the computations thus memory consumption should grow, right?
2. Batch size - similarly with longer sequences, computational graph should double with every next power of 2, thus increasing the memory consumption.
3. Length of transcription 
4.  Length of prediction - on the first few steps the predictions are full of garbage and ridiculusly long - does it influence the memory consumption?

Also, how is masking handled? If I end up with a batch that has one "big" sample and the rest are small, would the memory consumption be as if all samples in the batch were of the same length as the longest one or rather the padding which i assume occurs would be masked so that it does not contribute to the calculations? In that case only a batch that contains many long samples would cause a spike in memory consumption. 

What points me towards thinking that it works like the last thing I described is the fact that the memory consumption can get higher from epoch to epoch, which wouldn't happen if it simply encountered the longest sequence in the first epoch already.

**Comment by okuchaiev** [comment]
For QuartzNet (1) and (2) are the two biggest factors which determine GPU memory consumption.
In particular, the longest audio clip you'll encounter will determine the maximum memory needed (and it will OOM if you don't have enough). 
In our experiments on public datasets, we typically ignore fragments longer than 16.7 seconds (most of LibriSpeech data is shorter than that) during training.
Therefore, for your data, if your fragments are generally long - you might want to consider splitting them into shorter segments (<=16 seconds).
If your GPUs does not have enough RAM to handle a batch size you want - you can use "iter_per_step" command-line argument of quartznet.py. For example, if your batch size is 16 and iter_per_step=2, it would mean that optimizer will do the step every second batch (but will still accumulate gradients at every step), therefore making "algorithmic" batch size equal to 2*16=32.
Regarding padding - we pad and mask to the largest sample in the batch.

**Comment by kwasnydam** [comment]
Thank you for the quick answer and propositions! I will try the `iter_per_step` if I cannot deal with it in any other way. Let me also ask two followup questions.
 1. What is your intuition about number of labels influence on memory consumption and performance in general? In Polish, on top of the standard latin characters I have some additional letters/labels/graphems `ą | ć | ę | ł | ń | ó | ś | ź | ż` and from my observations thus far it seems to influence the memory consumption (I guess I need to educate myself better on the CTC Loss Function to understand it in-depth)

2. Also, a followup to the padding and longest sequence thing: Let's assume that the tensors are of shape `[batch_size, sequence_length, num_features]` (regardless of what is the actual order, the size remains the same, so let's stay with it for the purpose of this example) where `sequence_length` is the number of frames. Now assume two scenarios:
* the batch contains a single sample which is the longest in the corpora (highest `sequence_length`) and **the remaining samples are of `sequence_length` that is roughly corpora average.** (in short - one longest and rest relatively short)
* the batch contains a single sample which is the longest in the corpora (highest `sequence_length`) and **the remaining samples are of `sequence_length` that is very similar to this longest sequence.** (in short - one longest and rest also pretty long). 

Will the memory consumption be the same in both cases or will the latter be higher? The importance of this is that in case they are going to be equal, I can just eliminate the outliers from the training set and it would solve my problem, while in the latter I would rather try to reimplement the DataLoader or whatever the class is called so that it does not allow for construction of a batch that exceeds a certain <real_size> which would be defined as a total length of all sequences that form the batch. 

Sorry for the trouble and thank you for your time!

**Comment by okuchaiev** [comment]
thanks for your interest in NeMo and Quartznet! Below are some of the answers to your questions.

1. The number of labels (e.g. vocabulary size) has a negligible effect on the memory consumption for character-based CTC models like QuartzNet. For QuartzNet it really only affects the number of weights in the decoder (JasperDecoderForCTC) module. It can have an effect on the quality of the model (WER)
**VERY IMPORTANT** You need to turn OFF the normalization in AudioToTextDataLayer module: ``normalize_transcripts: false``. It is set to true by default and is only applicable to English language. Set it to false and do your own transcript normalization. Things to consider: lowercase everything, drop some punctuation characters, convert numbers like 25 -> "twenty-five" etc (really depends on you application domain).

2. The memory consumption for the two cases you've described should remain the same (and is determined by the largest length in the corpora). 
*Yes, it is a very good idea to eliminate the outliers from the training set*. This is what we do (e.g. eliminate examples with audio longer than 16.7 seconds) to some degree even for a "clean" dataset such as LibriSpeech.

Tips for improving your WER:
* You can try a smaller model if your dataset isn't that big. E.g. Try 15x3 or 15x1.
* Another suggestion - download our pre-trained English checkpoint for QuartzNet15x5 (https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5) and before training load encoder weights from this checkpoint.  Obviously, you can't do the same for Decoder since your language is different, but most weights are in the Encoder anyway and you may see a WER boost if you try training with pre-trained encoder (even if it is from another language). Set a smaller learning rate for an experiment like this and do not freeze anything.

Would be curious to know if you got any results

**Comment by OndrejGl** [comment]
Thanks for the info here.  I'd like to use your last suggestion, i.e. loading your English encoder, but I'd also like to freeze it and train the decoder only.  

I am using --load_dir parameter, pointing to the directory where only the encoder resides, but it seems like the encoder is not being loaded.  I have therefore replaced the decoder with some dummy decoder from other training, but is there some other elegant way?

Also, in quartznet.py, I include  encoder.freeze(), but I get:
AssertionError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.

from pytorch.  Any idea how to freeze it for training?
Thanks

**Comment by Dannynis** [comment]
Ive also encountered similar problems during the training of quartznet on k80 gpu, using librispeech-train-clean ive decreased the batch size to 8, and still got cuda out of memory. During one of the itertaions (that i wrraped in tqdm to follow the progreas) suddenly the memory usage spiked. I took the an4 example notebook and updated the jasperencoder to use the quartznet architecture, is i use the original an4 config after 1300 steps the net is still stuck in underfit. Any suggestions on what should i do?

**Comment by kwasnydam** [comment]
Hey, some updates from me. 

Thanks for mentioning the manifest normalization thing, I also stumbled upon it digging through the code and it was indeed causing my network to not work properly in the beginning. 

The memory problems seems to spur from my mistakes though, it may seem obivous but @Dannynis check if the batch_size is not hardcoded anywhere (I had it hardcoded for 32, so me changing the batch size in the config file did not bring any benefit...), also make sure that the parameter for max_duration is passed correctly to the training data layer (that was another mistake I had in my code).

As for the results, so far I have trained two QuartzNet 5x3 models, one on about 200h hours and one on 800h of audio, both for 100 epochs on a single Quadro RTX 5000 GPU with batch sizes of 16 and 32  and the results seem promising. For me, the network really starts to learn around halfway through the training on epoch 50/60, which was 2 days on the smaller and 4 days on a bigger model.

**Comment by Dannynis** [comment]
@kwasnydam thanks for the heads up, where exactly youve spoted the hard coded batch size ?

**Comment by Dannynis** [comment]
additional information to the issue: 
after 6 epochs that went good, suddenly during one of the iterations ive got 'CUDA out of memory'
with the following traceback.
strange situation because the previous epochs succeeded without any problems,
could the fact that the model had been saved few steps ago cause it somehow ?
Thank you :)  
![image](https://user-images.githubusercontent.com/27926192/77833368-d8af2980-714d-11ea-8655-c3490a7d68d8.png)

**Comment by kwasnydam** [comment]
@Dannynis In my case I have introduce the bug myself, I have built the training script around the example notebook https://github.com/NVIDIA/NeMo/blob/r0.9/examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb, which instantiates the DataLayer in the following way:

```
# Create training and test data layers (which load data) and data preprocessor
data_layer_train = nemo_asr.AudioToTextDataLayer(
    manifest_filepath=train_manifest,
    sample_rate=sample_rate,
    labels=labels,
    batch_size=32,
    **params['AudioToTextDataLayer']['train'])  # Training datalayer
```

And then I:
1. Didn't correct the `batch_size` line passing there my batch_size.
2. moreover, which was the actual reason for the OOM for me, I did not modify the way params are passed `**params['AudioToTextDataLayer']['train']`, and like this the `max_duration` param in `AudioToTextDataLayer` was not passed properly, because it is outside of the ['train'] dictionary:
```
AudioToTextDataLayer:
    max_duration: 16.7
    trim_silence: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null
```

So fixing this two and switching off normalization of manifests resolved my problems. 

About your problem (a few epochs passed and then it OOMs) check this issue, maybe it is related? https://github.com/NVIDIA/NeMo/issues/411

**Comment by OndrejGl** [comment]
Did you guys ever try to freeze the encoder and train the decoder only?

**Comment by jsilbergDS** [comment]
Where would one change iter_per_step? I can't find that as an argument in the nemo github repo? Thanks!

**Comment by titu1994** [comment]
Iters per step is deprecated. There should be no reason to use it, as it is replaced by pytorch lightning "max_steps" argument in Trainer.
