### ISSUE TITLE
What all parameters need to be changed and how in config, if i want to change min_duration in SSL_CONFORMER_PRETRAINING

### ISSUE THREAD

**Issue by mujhenahiata** [NVIDIA/NeMo#4856]
link to config: https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/ssl/conformer/conformer_ssl.yaml

when I change min duration to let's say 1.6 sec 
I get errors like 
RuntimeError: shape '[8, 44, -1]' is invalid for input of size 143360
RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement

what all parameters I need to change in order to run the experiment successfully
these are the few parameters I think need some updation.  
stride_layers
combine_time_steps
patch_size
mask_patches
num_negatives

**Comment by titu1994** [comment]
@sam1373 can you improve the tutorial with a section describing the relation between these parameters ?

**Comment by sam1373** [comment]
Hi @mujhenahiata, 
There is some explanation in the tutorial regarding these parameters, I will paste it here:

"Note that for this loss the outputs must match the inputs, so since we are using Citrinet architecture with 8x stride, we would need to either set "combine_time_steps" to 8, or put additional stride layers in the decoder. By default for Citrinet with 8x stride we use "combine_time_steps=4" and "stride_layers=1" to match the 8x stride.

Since in MaskedPatchAugmentation we set mask_patches to 0.5 and our min_durations are set to 3.2, we are guaranteed to have 1.6 masked second per utterance, or 160 masked steps. Since combine_time_steps is set to 4, this means that 160 / 4 = 40 total negatives can be sampled, so we set num_negatives to 40 (unless you set sample_from_same_utterance_only to false or sample_from_non_masked to true, but this tends to make results worse)."

For your case, in the conformer config by default we have stride 4 and combine_time_steps=4, thus no stride_layers. So if you want to use min_duration=1.6 then with 50% masked steps this would correspond to num_negatives=80/4=20, or you could set combine_time_steps=2 and stride_layers=1, which would allow num_negatives=40 (then you will need to also adjust the mlm decoder to correspond, or remove mlm loss). Though if you have a lot of utterances that are much longer in your dataset, it would be better to set min_duration higher.

**Comment by mujhenahiata** [comment]
what happens is, that when the min_duration is set to 8 sec, the majority of my files are filtered out. I am left with very few files in training,
@sam1373  the analogy works. 
thank you @titu1994 & @sam1373
