### ISSUE TITLE
significant parameter for tts with male speaker

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#4880]
Hi,
I am trying to train a TTS model (mixertts+univnet). the dataset contains male speakers voices.
Is there a parameter that needs to be changed to train these models with male speakers voices? Because the tone of the output voices are not very good.
Thanks in advance.

**Comment by redoctopus** [comment]
A few possibilities off the top of my head:

Have you updated the pitch statistics `pitch_mean` and `pitch_std` to reflect the speaker data? MixerTTS is meant for single-speaker training, are you mixing speakers for one model? That might lead to lower-quality output.

Also, are you using a pretrained Univnet or training it on the new data? If the latter, please also make sure that you are training using the generated spectrograms from MixerTTS rather than from the ground truth spectrograms.
