### ISSUE TITLE
Issue in ASR chunk inference

### ISSUE THREAD

**Issue by dbkalaria** [NVIDIA/NeMo#5059]
Hello, I'm trying to use the ASR chunk Inference script as the video I want too process is too big (2 hours). But getting an error while running the script. 

command I'm using `python .\speech_to_text_buffered_infer_ctc.py --asr_model="stt_en_conformer_ctc_xlarge" --test_manifest="video_2.wav" --model_stride=4`

Issue 
`Traceback (most recent call last):
  File ".\chunk_inference.py", line 169, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File ".\chunk_inference.py", line 132, in main
    hyps, refs, wer = get_wer_feat(
  File ".\chunk_inference.py", line 62, in get_wer_feat
    row = json.loads(l.strip())
  File "C:\Users\dhruv\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 5: invalid start byte`

**Comment by titu1994** [comment]
You can't pass a wav file as a manifest - `test_manifest="video_2.wav"` that's why you're getting a decoding error. 

What you can do is convert your video to pure audio waveform (16 khz, mono channel), create a single line manifest file containing `audio_filepath` and an empty `text: ""` value to get the transcript out of a single file

@VahidooX maybe we should check if text exists in manifest or not and ignore it if not present.

**Comment by dbkalaria** [comment]
Hello @titu1994, Yes I'm converting my video file using this command `ffmpeg -i {video_path} -ab 160k -ac 1 -ar 16000 -vn {audio_name}`. Is there any example on how to create a manifest file?

**Comment by titu1994** [comment]
There's multiple docs and tutorials showing how to write a manifest file for asr, please review the introduction to asr tutorial.
