### ISSUE TITLE
[TTS] DE Multi-Speaker FastPitch HiFiGAN Tokenization Error

### ISSUE THREAD

**Issue by inOXcrm** [NVIDIA/NeMo#5466]
When following the basic instructions [here](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/tts_de_fastpitch_multispeaker_5): 
just replace the text promp with: "hallo wie geht es ihnen?" - German for "Hello, how are you doing?"

This occours: 

[hallo wie geht es ihnen?] contains unknown char: [g]. Symbol will be skipped.

**Expected behavior**

The letter "g" is commonly used in the German alphabet and is essential to pronunciation of certain words. It seems that this issue is related to the trained models that are provided under that link.

**Comment by aeciorc** [comment]
I believe it's because the tokenizer target in the [configuration](https://github.com/NVIDIA/NeMo/blob/main/examples/tts/conf/de/fastpitch_align_44100.yaml#L69) for the multispeaker model is:
`nemo.collections.common.tokenizers.text_to_speech.tts_tokenizers.GermanPhonemesTokenizer`

which does not have those [chars](https://github.com/NVIDIA/NeMo/blob/stable/nemo/collections/common/tokenizers/text_to_speech/tts_tokenizers.py#L300). It should probably point to [GermanCharsTokenizer](https://github.com/NVIDIA/NeMo/blob/stable/nemo/collections/common/tokenizers/text_to_speech/tts_tokenizers.py#L195), like in the config for the singlespeaker model (which doesn't have this issue). I'll let someone more experienced than me answer this though, maybe @XuesongYang can confirm?

**Comment by inOXcrm** [comment]
@aeciorc This still means that the model has to be retrained, right?

**Comment by XuesongYang** [comment]
> @aeciorc This still means that the model has to be retrained, right?

At the current stage, the answer is yes. You have to replace it with `GermanCharsTokenizer` and train models again following https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_GermanTTS_Training.ipynb

**Comment by inOXcrm** [comment]
I have retrained the FastPitch model, you can find it here: https://huggingface.co/inOXcrm/German_multispeaker_FastPitch_nemo

**Comment by XuesongYang** [comment]
> I have retrained the FastPitch model, you can find it here: https://huggingface.co/inOXcrm/German_multispeaker_FastPitch_nemo

Awesome! We are refactoring TTS collection a little bit, please let us know if you hit errors.

**Comment by inOXcrm** [comment]
Ran into an issue when trying to run the model on newer nemo version: 

hydra.errors.InstantiationException: Error in call to target 'nemo.collections.common.tokenizers.text_to_speech.tts_tokenizers.GermanCharsTokenizer':
TypeError("GermanCharsTokenizer.__init__() got an unexpected keyword argument 'phonemes'")
full_key: text_tokenizer

Can this be an effect of refactoring? If so, how can I fix it without retraining the entire model again?
