### ISSUE TITLE
All files present in manifest contains silence, aborting next steps

### ISSUE THREAD

**Issue by skanda1005** [NVIDIA/NeMo#5743]
**Describe the bug**

All files present in manifest contains silence, aborting next steps. 
When I run the diarization with an audio file which contains no speech, it terminates the program and throws an error

**Steps/Code to reproduce bug**

Run diarization on any audio wav file which contains no speech/audio

**Expected behavior**

Rather than program terminating, I would like a blank output and a blank rttm file.
Or how do I circumvent the "raise ValueError" in the script?

**Comment by tango4j** [comment]
Hi, thank you for suggesting.
Since speaker diarization is also affecting other modules so it should notify the user that silence has detected at diarization step. 
We should also consider the case where the input audio is so noisy that VAD cannot detect any speech segment. This kind of situation should not be considered as an error, where all the functions/models are functioning properly.

Please make your own fork regarding this if you really need so.
Also changing this to feature request since this is not a bug.

**Comment by Swami-Abhinav** [comment]
got the same issue

**Comment by salimkt** [comment]
Same issue
