### ISSUE TITLE
Use `mypy` for type checking

### ISSUE THREAD

**Issue by artbataev** [NVIDIA/NeMo#5894]
**Is your feature request related to a problem? Please describe.**

In many places in NeMo, Python type annotations are used.
Since type annotations are not checked, there are some cases where annotations are incorrect or not precise (e.g., using one type when some union is really used).

**Describe the solution you'd like**

Add `mypy` type checking support. 

**Main principle:** do not require types, but if types are provided, check (require) correctness.

- firstly, add a minimal PR that doesn't affect existing code (except 2 lines, since duplicated type annotations are critical errors for mypy)
- provide PRs one-by-one to fix some of the errors to improve code quality, removing the error types from ignore list.

**Describe alternatives you've considered**

[Pyre](https://github.com/facebook/pyre-check) also can be considered as an alternative, but `mypy` is usually used as a default choice.

**Additional context**

...

**Comment by artbataev** [comment]
This is an issue for a discussion. If we agree on a concept, I will provide the PR

**Comment by artbataev** [comment]
@ericharper, @titu1994, @okuchaiev, @Kipok, @SeanNaren let's discuss the approach and potential issues. I can provide the first PR, if it is ok.

**Comment by Kipok** [comment]
I like the idea - I think if we use types, we better check them in the CI. It's better to not have types at all than to have incorrect types. And not checking them inevitably leads to incorrect types at some point.

**Comment by titu1994** [comment]
> It's better to not have types at all than to have incorrect types

Disagree here. It is disingenuous to create a union type of dozens of possibilities. It does not help anyone. For a common case, look at Hypothesis object of RNNT decoding. There's dozens of flags, many of which are overloaded and dynamic. 

Should we abandoned type entirely ? Ofc not - some of the types are primary use cases. They are overloaded by later stages. Should we have a union ugly type of dozens of possible types? Ofc not, that's not helpful. 

Mypy has to be optional and disabled either in a code location or in a file entirely similar to neural types

**Comment by artbataev** [comment]
> Disagree here. It is disingenuous to create a union type of dozens of possibilities. It does not help anyone. For a common case, look at Hypothesis object of RNNT decoding. There's dozens of flags, many of which are overloaded and dynamic.
Hm, I don't see a contradiction.
If you mean that reassigning a value of different type, it is totally ok.
```python
a = 1
# do something with int
a = "one"
# do something with string
```

But if we have a function that is annotated as returning `int`, this will be incorrect:
```python
def some_function() -> int:
    if <condition>:
        return 1
    if <condition>:
        return "one"
    return None
```

But no annotation or `def some_function() -> Any` will be better (and always should be allowed).

**Comment by Kipok** [comment]
> Should we have a union ugly type of dozens of possible types? Ofc not, that's not helpful.

You might be right, but I'd also argue that if we see a situation where a single variable can take a dozen of possible different types - that probably indicates that this code is too complicated and needs to be refactored into something simpler.

And in my opinion for those cases, it is better to not have types at all (hopefully there are not too many such cases in our codebase). At least for me, when I see that something is explicitly typed in the code, I assume that it should be correct. And if I commonly see cases where it's not correct, I simply start ignoring the types when reading the code, because I can't trust them.

> Mypy has to be optional and disabled either in a code location or in a file entirely similar to neural types. It absolutely should not enforce an either do everything or nothing stance.

Agree with this, we should make it flexible and allow for explicit disable in some places, where it currently makes sense. That being said, I also think we should strive to make sure it's enabled in all of the codebase eventually.

**Comment by titu1994** [comment]
> that probably indicates that this code is too complicated and needs to be refactored into something simpler.

It's not code being complicated, it's the requirement of having a container return type for functions as generic as transcribe - do you recommend having a dozen transcribe functions such as 
- transcribe CTC char 
- .. CTC bpe 
- .. RNNT char 
- .. RNNT bpe
- ASR TTS char / bpe
- hybrid CTC RNNT char / bpe
- x product of all above with beam search 
- x product of all above with other tasks of the future (confidence measurement, timestep calculation, alignment, etc)

No. Users and I myself want a generic model.transcribe() to do all that with a simple interface, and the result of that is a very overloaded output type. 

Can we refactor the Hypothesis dataclass into 50 different classes? Sure. Should we / would it benefit anyone ? Not really. It would inflict overhead in trying to determine what the type is and then acting specific for each returned types. That's unrealistic. 

> And in my opinion for those cases, it is better to not have types at all (hopefully there are not too many such cases in our codebase

For all that overloaded responsibilities of Hypothetical, we do still have types. Is it lose typing ? Yes. Is it useful even though it's loosely typed ? Absolute yes. Ask anyone who has had to add functionality to ASR transcribe. Types, even when loosely defined, are absolutely useful. 

Any as a type is not useful in such a trivially  scenario. What does it add to my knowledge other than wasting space on a screen ? Why do we use hydra and declare data classes if I can use any everywhere ?

I do agree with @Kipok that we should strive where it is feasible to annotate our code with types. However strive and mandates are two very different things. I am opposed to a "mandated" approach, and saying "just use Any" is not helpful. That is still mandatory, and completely without any value at the same time. 

My request is as follows : 
Typing must be allowed to be loosely defined - that's why we used neural types as a completely optional decorator. Yet, a good chunk of ASR classes (at least the more recent ones), we have tried to add loose types to most functions or signatures. We can do better here, sure, but that does not mean we should be forced to hammer out every niche type and case of every single function or class. That is absurd and simply damages development of research code. 

Please always remember that NeMo is first and foremost a research toolkit, not a bastion of perfect production code. We will attempt to enforce good practices, but they are not an ironclad rule that absolutely cannot be violated. 
Any unnecessary burdon inflicted on this front will not be enforced.

**Comment by Numeri** [comment]
I at least would be very happy with increased typing in NeMo and would be glad to contribute towards that.

**Comment by sakgoyal** [comment]
A lot of the complex types can be defined with the generics that python has now. IDEs also offer good type inferences so strongly defining everything is not nessesary. But not adding types at all is not great. it makes it harder to self discover the available APIs. 

even if you try to add a few types in some places, it massively helps out the LSP to see what types exist where and make inference better.
