### ISSUE TITLE
Logprob for stt_conformer_transducer_large

### ISSUE THREAD

**Issue by efyphil** [NVIDIA/NeMo#6402]
The Quartz model uses [logprobs](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/Offline_ASR.ipynb#scrollTo=ZhWmR7lbvwSm) , which are very helpful in assessing how well speech is spoken. They make it possible to construct a spectrogram, but it is inferior to the model stt_conformer_transducer_large. Is it possible to get log samples or something similar for this model? Maybe I don't know something and there are other ways to get probabilities for tokens in this model?Thanks in advance for the answer

**Comment by titu1994** [comment]
Transducer models do not compute the full joint logprobs tensor of shape [B, T, U, V+1] during inference since that is not needed, unlike CTC which does compute the logprobs tensor of shape [B, T, V+1]. 

You can instead get the 2d alignment of RNNT models which is the inference equivalent of the CTC logprobs tensor - https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_with_Transducers.ipynb#scrollTo=dpUoqG_G6DII
