### ISSUE TITLE
How to get the intermediate features from the pre-trained checkpoint

### ISSUE THREAD

**Issue by msh9184** [NVIDIA/NeMo#6535]
Hi @titu1994, @VahidooX, thank you for your hard work.

I am trying out an experiment for the knowledge distillation task by utilizing the official pre-trained checkpoint ([stt_en_conformer_ctc_large_ls](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_ctc_large_ls)) for the teacher model.

I would like to extract some intermediate features from this pre-trained teacher model (i.e., the self-attention layers in the conformer blocks), but all the intermediate layers in `ConformerEncoder` module seem to be overwritten with the variable `audio_signal`.

Is there a way to get these intermediate layers from the pre-trained checkpoint you provide?
I'd be grateful if you could provide some tutorials or tips.
Thank you.

**Comment by VahidooX** [comment]
We don't have this feature currently. You may add such a feature by passing an empty list to the forward method of the encoder and then append the activations you need to the list.

**Comment by titu1994** [comment]
Intermediate features are not exposed since it requires additional memory to cache them. The best bet would be to create a new NeMo model that perform the forward pass of the conformer layer layer by layer to store the values you need. 
There are ways to do this generally such as the AccessMixin however that can cause memory leaks if you're not careful.

**Comment by msh9184** [comment]
Thank you so much.
