### ISSUE TITLE
我在测试tutorials/tts/FastPitch_ChineseTTS_Training.ipynb中，发现对于AI两个字母不起效果

### ISSUE THREAD

**Issue by bank010** [NVIDIA/NeMo#7302]
**Describe the bug**

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` 

https://github.com/NVIDIA/NeMo/assets/107624041/ef36be57-6419-4574-b618-d0b4c65d7e3d

& `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by XuesongYang** [comment]
yes, english pronunciation is not good because we have very limited English resources in SFSpeech. The tutorial demonstrated how to train a Chinese model rather than a English/Chinese bilingual model. The english symbol set only contains graphemes, while chinese contains phonemes. If you are interested in multi-lingual modeling, I would suggest,
1. fine-tune your model on top of pre-trained English checkpoint;
2. (and/or) add a canonical g2p dict to transliterate English words into phonemes.
