### ISSUE TITLE
scp_to_manifest like script?

### ISSUE THREAD

**Issue by yuekaizhang** [NVIDIA/NeMo#743]
Hi,

My question is about data prep part. I notice that Nemo has separate scripts for different dataset, e.g. get_librispeech_data.py, process_aishell_data.py. Also, you have scp_to_manifist.py which is for spkid. Do you have some scp_to_manifest script for ASR? For example, convert kaldi or espnet data/wav.scp and data/text into one nemo json file? In this case, you could conduct experiments in kaldi or espnet egs quickly using nemo. 

If you already have, may I ask you to get that script?
Or I'd love to write a script to PR if you think it is helpful.

**Comment by redoctopus** [comment]
Though we do have the [KaldiFeatureDataLayer](https://nvidia.github.io/NeMo/collections/nemo_asr.html#nemo.collections.asr.data_layer.KaldiFeatureDataLayer), it's only intended for loading feats.scp rather than wav.scp.

We don't have a script for conversion to a NeMo-style manifest, so you are welcome to write that script if you'd like!
