### ISSUE TITLE
Output .ctm of Speech Data Simulator has channel and spk_id swapped 

### ISSUE THREAD

**Issue by popcornell** [NVIDIA/NeMo#7445]
https://github.com/NVIDIA/NeMo/blob/2cc09425aba3e9b3cfdba43a3188eaef58227055/nemo/collections/asr/data/data_simulation.py#L1057

But according to https://web.archive.org/web/20170119114252/http://www.itl.nist.gov/iad/mig/tests/rt/2009/docs/rt09-meeting-eval-plan-v2.pdf it should be: 

```
<SOURCE><SP><CHANNEL><SP> <BEG-TIME><SP><DURATION><SP><TOKEN><SP>
<CONF><SP><TYPE><SP><SPEAKER><NEWLINE>
```

**Comment by tango4j** [comment]
Hi, @popcornell .
This is intended since we were creating dataset where all channels share the same word alignment 
so we used channel slot as speaker.
I think this needs to be updated to have consistency with the CTM convention in RT09 document.
I will keep this open until this gets fixed.

**Comment by popcornell** [comment]
Hi Taejin, thanks for the reply. 
I like a lot the data simulator, it is very fast and really helpful, I used it in a recent work. 

I can actually fix this it is pretty easy, I have already done so locally. 
I needed consistency with RT09 convention because I was using lhotse https://github.com/lhotse-speech/lhotse for dataloading and having .ctm was quite handy for loading in the manifests also the word alignments.

> This is intended since we were creating dataset where all channels share the same word alignment
> so we used channel slot as speaker.

There is a channel slot in the .ctm convention but IDK if it is what you need.

**Comment by tango4j** [comment]
Oh I see.
This definitely needs to be updated ASAP.
Also Piotr Zelasko <pzelasko@nvidia.com> joined NVIDIA NeMo team, so
I think I could let him go through the PR to make sure the compatibility with lhotse.
@KunalDhawan

**Comment by tango4j** [comment]
Just FYI.
We are trying to fit NeMo data-sim and CTM format to Lhotse and RT09
for better compatibility.

Best,
Taejin Park

From: Samuele Cornell ***@***.***>
Date: Tuesday, October 17, 2023 at 3:57 PM
To: NVIDIA/NeMo ***@***.***>
Cc: Taejin Park ***@***.***>, Assign ***@***.***>
Subject: Re: [NVIDIA/NeMo] Output .ctm of Speech Data Simulator has channel and spk_id swapped (Issue #7445)

Hi Taejin, thanks for the reply.
I like a lot the data simulator, it is very fast and really helpful, I used it in a recent work.

I can actually fix this it is pretty easy, I have already done so locally.
I needed consistency with RT09 convention because I was using lhotse https://github.com/lhotse-speech/lhotse for dataloading and having .ctm was quite handy for loading in the manifests also the word alignments.

This is intended since we were creating dataset where all channels share the same word alignment
so we used channel slot as speaker.

There is a channel slot in the .ctm convention but IDK if it is what you need.

**Comment by popcornell** [comment]
I have a PR that addresses this now.
