### ISSUE TITLE
Finetuning hifigan

### ISSUE THREAD

**Issue by pragyachaturvedi99** [NVIDIA/NeMo#7473]
**Hydra conf path not found**

I have been trying to run fastpitch_finetune.ipynb and from inside the nemo docker container. While the code ran bug free till inference of fastpitch model, when I am trying to run the steps given to run hifigan_finetune.py it throws an error related to config path

Primary config directory not found.
Check that the config directory '/TTS/conf/hifigan' exists and readable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Or 
path not present in hydra_search_config.

I have been running it on a vm instance with a t4 gpu.
Please reach out if you know why this is happening and how to resolve this.
I have checked hydra directory for this error and tried a few solutions from there the problem is persistent.

**Comment by XuesongYang** [comment]
at first glance, the root cause may be the wrong combo of config path and name. Could you have another try by specifying for example below,
 
*Current Config with Errors*:
--config-name=/TTS/NeMo/examples/tts/conf/hifigan/hifigan.yaml
 
*Corrected Config*:
--config-path=/TTS/NeMo/examples/tts/conf/hifigan
--config-name=hifigan.yaml
