### ISSUE TITLE
Verbosity showing while training standard ASR model

### ISSUE THREAD

**Issue by TonSotin** [NVIDIA/NeMo#7810]
Is it possible to change verbosity of a pretrained model while training?
When I train with modified vocab it always show me prediction and reference, but if it's a standard model nothing has shown.

**Comment by nithinraok** [comment]
change `https://github.com/NVIDIA/NeMo/blob/5f8e06d3b0e21a9276aafc5466bee67190a4fdfb/examples/asr/conf/conformer/conformer_transducer_bpe.yaml#L258` to a larger number

**Comment by TonSotin** [comment]
I have `log_every_n_steps` parameter value set to 1. And I still can't see reference and prediction while training. Are you sure that `log_every_n_steps` parameter is responsible for that?

**Comment by titu1994** [comment]
You need to also set the model.log_predictions=True https://github.com/NVIDIA/NeMo/blob/5f8e06d3b0e21a9276aafc5466bee67190a4fdfb/examples/asr/conf/conformer/conformer_transducer_bpe.yaml#L258

This is usually disabled by default in order to avoid wasting time calculating predictions for rnnt (autoregressive decoding) plus moving metrics and results from GPU to CPU all of which slows down training
