### ISSUE TITLE
Inquiry about Pull Request #1008: Added support for phonetic lexicon

### ISSUE THREAD

**Issue by csetanmayjain** [NVIDIA/NeMo#7815]
Dear Team,

In the pull request #1008 discussion, I noticed a mention of a feature related to utilizing a custom lexicon dictionary during the training process. But after a few updates, I can't see that feature in the latest releases. Seems there might have been some changes or removal of this feature since that time. To be more specific, I'm curious to know:

1. Whether the aforementioned pull request introduced a feature for utilizing a custom lexicon dictionary during the training process.
2. If such a feature was introduced, has it been subsequently removed from the codebase?
3. If it has been removed, could you please shed some light on the reasons behind this decision?

[GitHub Pull Request #1008](https://github.com/NVIDIA/NeMo/pull/1008)

Thanks :)

**Comment by vsl9** [comment]
Dear Tanmay,

The PR was not merged because it is pretty trivial and not very interesting for most NeMo users. 

The PR implemented a phoneme-based QuartzNet: the ASR model was trained to predict phonemes instead of characters (letters). In order to train the model, the data loader required a grapheme-to-phoneme (G2P) dictionary (a phonetic lexicon like CMUdict) to convert ground truth transcripts to sequences of phonemes. 

Most ASR users are interested in getting text as a prediction (and not a sequence of phonemes). We experimented with that model as a helper model to find alignment of phonemes and audio for TTS problem. But at the end of the day, RAD-TTS Aligner provides a better way to get the alignment: https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/tts/Aligner_Inference_Examples.ipynb

**Comment by csetanmayjain** [comment]
Dear Vitaly,

I was curious if there are any results from your benchmarking efforts that compared the performance of phoneme-based and other tokenizer models in the NeMo ASR framework.

For my particular use case, I am interested in conducting tests and benchmarking experiments with both phoneme-based and subword-based tokenization. Could you kindly confirm whether this pull request is sufficient for training a streaming ASR model based on phonemes using the Conformer CTC architecture?

Your insights will be greatly appreciated. Thank you for your time and assistance.

**Comment by csetanmayjain** [comment]
Thanks
