### ISSUE TITLE
CTC segmentation tool does not support fastconformer hybrid model

### ISSUE THREAD

**Issue by yunbin** [NVIDIA/NeMo#7831]
**Describe the bug**

It seems stt_en_fastconformer_hybrid_large_pc is supported by the force alignment tool, but not the CTC segmentation tool. CTC segmentation tool works on older models, but not the ctc rnnt hybrid model

./NeMo/tools/ctc_segmentation$ ./run_segmentation.sh  crash on latest stt_en_fastconformer_hybrid_large_pc model.

**Steps/Code to reproduce bug**
 
     NeMo/tools/ctc_segmentation$  ./run_segmentation.sh --MODEL_NAME_OR_PATH="stt_en_fastconformer_hybrid_large_pc" --DATA_DIR=./data/timit --OUTPUT_DIR=./res/timit_fastconformer_hybrid_large_pc

**Expected behavior**

 code crash with error message:    
    ctc_segmentation/scripts/prepare_data.py", line 357
    omegaconf.errors.ConfigAttributeError: Key 'vocabulary' is not in struct

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

- OS version    ubuntu "20.04.6 LTS (Focal Fossa)"
- PyTorch version     2.1.0           py3.10_cuda11.8_cudnn8.7.0_0
- Python version      3.10.12 

**Additional context**

**Comment by yunbin** [comment]
Right, you may want to merger these two tools into one. It is confusing and harder to maintain two. It will be nice to merge the CTC segmentation function into the forced alignment tool.

**Comment by titu1994** [comment]
Not really, they are two entirely different things. NFA is more general alignment tool used for getting timestamps of tokens. You can use that timestamps for many different things, one of which is segmentation. Ctc segmentation is a special case that handles just segmentation, and does it well with CTC framework model. It has some fallbacks of more or less accurate segments etc, all of which can be implemented by the more general NFA but requires more work to do so. 

So you can think of NFA as the general tool, and CTC segmentation as a special case of that tool. Btw, with some hand written logic, you can very well use NFA for segmentation as well.

**Comment by yunbin** [comment]
Right, that is why I thought it is better to merger them into one tool, and with a specials flag the new merger tool can do the specials task of segmentation.

**Comment by FredSRichardson** [comment]
We did make the changes necessary for the tool to run with the new hybrid CTC RNNT models.  This really came down to a few basic changes:
1. setting `bpe_model` variable to True if the model is a `EncDecCTCModelBPE` or a `EncDecHybridRNNTCTCBPEModel`
2. adding a variable `rnnt_model` which True if the model is a `EncDecRNNTModel`
3. throwing an exception if `rnnt_model` is true but the mode is not a `EncDecHybridRNNTCTCModel` - the non-hybrid RNNT models do not return posteriors from the `transcribe()` method...
4. if `rnnt_model` is True, set the decoding type to 'ctc' for the model (call `change_decoding_strategy(decoder_type='ctc')` and get the vocabulary from the `['aux_ctc']['decoder']['vocabulary']` field of the models config
Non-hybrid RNNT models could be supported but posteriors would have to be extracted by calling the `forward()` method since the `transcribe()` method does not return these.

**Comment by titu1994** [comment]
This is awesome thanks ! Rnnt does not support returning a posterior matrix since it's computed at run time and is usually a dangling matrix - rnnt can predict more than one token at a given timestep

**Comment by gabitza-tech** [comment]
Hi, 

A quick question, would the aligner work on the outputs from a CTC model combined with a language model?

BR,
Gabi

**Comment by titu1994** [comment]
Not really. Theoretically may be possible but practically I don't think any aligner uses lm during viterbi decoding. Maybe @erastorgueva-nv may know

**Comment by FredSRichardson** [comment]
@titu1994  - I took a look at the `training_step()` method for the RNNT model - it looks like you can get posteriors from that model using two steps: basically calling the `forward()` followed by the `joint()` method.  For the Hybrid CTC RNNT model you can get CTC posteriors by calling the `forward()` method followed by invoking the `ctc_decoder` member (which is really an instance of a decoder).  It seems to me that having posterior computation called in a consistent way across models would be really helpful, and it might also be nice if there was a way to "adapt" a hybrid RNNT CTC model so that it behaves like a CTC model when that is how you are using it (that is all the methods perform the same way).  As it is not quite a lot of code needs to change to support these slightly different model APIs...  I started an issue on this here:  https://github.com/NVIDIA/NeMo/discussions/7839

**Comment by titu1994** [comment]
You can get the RNNT posterior only during training. Constructing the posterior also takes exorbitant amounts of memory, 2-3 order of magnitude more than the equivalent ctc, which makes it useless as a segmentation tool for long audio
