### ISSUE TITLE
Unexpected Space Removal Before Punctuation in ASR Model Decoding

### ISSUE THREAD

**Issue by asheryuval** [NVIDIA/NeMo#8041]
Hello,

I've come across an issue in the `nemo/collections/asr/metrics/wer.py` file, specifically within the `decode_hypothesis` function. There's a particular segment of code, marked for future removal (noted with a TODO comment) at line 546, which I believe should be eliminated.

This issue becomes apparent during the training of models that include punctuation marks as separate tokens, mirroring the ground-truth data which incorporates spaces preceding these punctuation marks. The problematic code collapses these spaces during decoding, resulting in significantly higher WER and loss calculations due to mismatches in space formatting. This code segment appears redundant when training models without punctuation marks, as it has no effect in such scenarios. It only impacts models trained with punctuation in the specific context I've outlined.

For instance, consider the ground-truth data: `This is a test , with some extra spaces .` and its prediction: `This is a test, with some extra spaces.` This alters the prediction by removing spaces before the punctuation marks.

Here's the code snippet:
`# TODO: remove`
` # collapse leading spaces before . , ? for PC models`
` hypothesis = re.sub(r'(\s+)([\.\,\?])', r'\2', hypothesis)`
`
Could you please confirm if you're aware of this and if there are plans to remove this section of code?

Thank you

**Comment by titu1994** [comment]
We are aware of this, hence the Todo to remove it. But our condition for removal is that we update all the PC models we release such that they do not have spaces between special tokens. So the removal won't have an effect at that point since all the models will anyway emit no space between special tokens. 

The simplest solution to this problem is to collapse the space between special tokens in both the ground truth and the predicted models, rather than keep the spaces and anyway get incorrect metrics during inference.
