### ISSUE TITLE
Finetuning ASR models and change the vocabulary error！！！

### ISSUE THREAD

**Issue by h310558606** [NVIDIA/NeMo#8115]
My code:
....
model = nemo_asr.models.ASRModel.from_pretrained("stt_en_citrinet_512")
model.change_vocabulary(
    new_tokenizer_dir="./tokenizers/an4/tokenizer_spe_unigram_v32/",
    new_tokenizer_type="wpe"
)

**error:
You tried to register an artifact under config key=tokenizer.vocab_path but an artifact for it has already been registered**.
![1704261547987](https://github.com/NVIDIA/NeMo/assets/38098690/61c3d694-a2fe-487c-9f23-9cf34e8cf0c9)

**Comment by titu1994** [comment]
That's more of a warning than an error. The actual crash is because of the OSErrorv- network is unreachable. HF wpe requires connecting to the HF servers when for local models, you need to use the environment flag TRANSFORMERS_OFFLINE=1 (or set that in os.environ before importing HF). 

Otherwise you can create and use a sentence piece tokenizer instead (recommended)
