### ISSUE TITLE
White noise pertrubation can exceed [-1,1] range

### ISSUE THREAD

**Issue by bagavi** [NVIDIA/NeMo#854]
White noise perturbation adds white noise to the data samples ([here](https://github.com/NVIDIA/NeMo/blob/master/nemo/collections/asr/parts/perturb.py#L288)). For high amplitude noise (say 0db), the perturbed data samples could exceed the [-1,1] range. Is this a problem or are the data samples re-normalized later?

**Comment by vsl9** [comment]
It should be ok, since we are not working with integer values and there is no numerical overflow. Regarding re-normalization, ASR models usually have it on mel spectrogram features (before the first layer): https://github.com/NVIDIA/NeMo/blob/3d6ae0589c1bf0fed2cb038ac80590bebe738e3d/nemo/collections/asr/parts/features.py#L277

**Comment by bagavi** [comment]
Thanks for the answer!
