### ISSUE TITLE
Can I finetune from a sub-word based model to a character based model ?

### ISSUE THREAD

**Issue by hoangtm-aimesoft** [NVIDIA/NeMo#8774]
Hi. First of all, thank you for your great work!
I 've followed the ASR language finetuning tutorial. In this tutorial, you finetuned character-based model and sub-word based model from English to corresponding model type in Japanese. I have a question, can I finetune from a sub-word base model in English to a character-based model in Japanese ?

**Comment by titu1994** [comment]
Yes it's quite easily doable. What you can do is build a sentence piece "char" tokenizer instead of "bpe" or "unigram" - the char spe tokenizer provides a character encoding but with similar API to subword one so model can continue working with just change_vocabulary(). 

The only think to watch out for is if you're using CTC models, then you need to test that your audio length / text length ratio is always about 1.1 or 1.2 (we have a test for this in the eng to japanese tutorial). If not, your model will fail to train.

**Comment by chnk58hoang** [comment]
Thank you for your reply

**Comment by hoangtm-aimesoft** [comment]
Thank you ! Now I'm having a 70-hours Japanese dataset and I want to finetune from Character based ConformerTranducer pretrained on Mandarin. Can you give me some advice about hyper params selections (lr, batch size, warm up steps , ...) ?
