### ISSUE TITLE
Speaker Diarization goes haywire due to small segments of audio

### ISSUE THREAD

**Issue by AatikaNazneen** [NVIDIA/NeMo#9523]
**Describe the bug**

I have a long audio of around 3 hours that spans multiple speakers. The speaker diarization label a single speaker when this audio is passed. When I break down into this audio in parts and pass each part separately, some of the parts get assigned speakers correctly but the rest of the portion has the same bug. I identified some 1 min chunks that when added in this audio cause the model to behave this way. I'm seeking possible explanations or solutions to this behavior since I believe that the model should be resilient enough.

I think this might be related to having lots of overlap and a good number of speakers resulting in exceeding Nemo's limit of 20 max speakers.

**Steps/Code to reproduce bug**

Test Speaker Diarization on the [audio]( https://21133.mc.tritondigital.com/OMNY_DAVECHUCKTHEFREAKFULLSHOW_P/media-session/ba27cae7-9871-409f-b206-2183ad4628fe/d/clips/58a22c8d-1810-4cd1-bce2-a849004eeede/f545c88c-6f30-414d-b85a-aff10125b149/17c6c4c0-70cb-4c39-b16b-b18000f52f46/audio/direct/t1717081258/Thursday,_May_30th_2024_Dave_Chuck_the_Freak_Full_Show.mp3?t=1717081258&utm_source=Podcast%26in_playlist%3D9857b359-5905-4672-a201-aff10125b173)

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: AWS
 - Method of NeMo install: pip install

**Environment details**

- AWS Linux 2
- PyTorch version: 2.3.1
- Python version: 3.10

**Additional context**

GPU model

**Comment by tango4j** [comment]
Please note that clustering based speaker diarization is a type of self-supervised machine learning system, not a rule-based software. Thus, speaker diarization can generate incorrect results. 

Especially, there is no guarantee that the speaker diarization system would generate the same speaker assignment to the truncated shorter audio clips from the original audio clips.

Closing since there is no clear ways to avoid this case.
