### ISSUE TITLE
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' while importing from nemo.collections.asr.models import EncDecMultiTaskModel

### ISSUE THREAD

**Issue by byColton** [NVIDIA/NeMo#9793]
I am attempting to use the tutorial code found on huggingface's ''. While importing from nemo.collections.asr.models import EncDecMultiTaskModel I produce the following code. ImportError: cannot import name 'ModelFilter' from 'huggingface_hub'. I have matched the HF package in the requirements documents.

File --------------------[lib/python3.10/site-packages/nemo/core/classes/common.py:31](http://localhost:8888/home/colton/anaconda3/envs/beer_crawl/lib/python3.10/site-packages/nemo/core/classes/common.py#line=30)
     29 import torch
     30 import wrapt
---> 31 from huggingface_hub import HfApi, HfFolder, ModelFilter, hf_hub_download
     32 from huggingface_hub.hf_api import ModelInfo
     33 from omegaconf import DictConfig, OmegaConf

ImportError: cannot import name 'ModelFilter' from 'huggingface_hub'

**Comment by rtaylo45** [comment]
NeMo is notorious for not pinning their versions (`huggingface_hub>=0.20.3` in requirements.txt). `huggingface_hub` released an new version 2 days ago ([release notes](https://github.com/huggingface/huggingface_hub/releases/tag/v0.24.0)). That might be whats causing the issue, especially if you did a fresh install of the `nemo-toolkit` from pip. I recommend doing a forced reinstall of `huggingface_hub` to its previous version and see if that helps. 

I am also running into this problem but at the time of writing this message, I have not tried out the recommended solution. Hope this helps!

**Comment by M-Usman-Dev** [comment]
**This issue is likely caused by a version mismatch between the nemo_toolkit and the huggingface_hub package.** 

> ModelFilter and DatasetFilter are completely removed

By matching the `huggingface_hub` version to `0.22.0`, I was able to resolve the import error. If you are using `nemo_toolkit==1.23.0`, this version of `huggingface_hub` should work.

I hope this helps others facing the same issue!

**Comment by vygodisgreat** [comment]
When I install `huggingface-hub==0.22.0` it says
```
ImportError: huggingface-hub>=0.23.2,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.22.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

**Comment by mtanana** [comment]
Thanks @vygodisgreat -  that fix worked for me (huggingface-hub==0.23.2)

**Comment by thinhlx1993** [comment]
Install huggingface-hub<0.24.0 works for me.

**Comment by jugal-sheth** [comment]
Has anyone successfully solved this can you please share your env.yaml or requirements.txt along with python version please

**Comment by AK3847** [comment]
After trying a bunch of configurations, this set seems to work for me without any version mismatch error.
```bash
!pip install transformers==4.40.0
!pip install huggingface_hub==0.21.3
!pip install tokenizers>=0.21
!pip install datasets==2.19.0
```

**Comment by Dev-iL** [comment]
`ModelFilter` was removed in [huggingface-hub v0.24](https://github.com/huggingface/huggingface_hub/commit/bb38f9422cb88ba02694c87fb5979cc48ecef8a0#diff-1b045ed2e860a78218b3501b6b8df1f5609c493c1e2fa16769486fb020f7c164), so requiring  `huggingface_hub<0.24` should do the trick.

**Comment by philm001** [comment]
I tried the command:

!pip install huggingface_hub==0.21.3

And I still got the error

**Comment by AK3847** [comment]
> I tried the command:
> 
> !pip install huggingface_hub==0.21.3
> 
> And I still got the error

You need to change versions of other packages as well to avoid new version conflicts, try this:
```
!pip install transformers==4.40.0
!pip install huggingface_hub==0.21.3
!pip install tokenizers>=0.21
!pip install datasets==2.19.0
```

**Comment by philm001** [comment]
```
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-3-424875f6207b>](https://localhost:8080/#) in <cell line: 0>()
----> 1 import nemo.collections.asr as nemo_asr
      2 import nemo.collections.nlp as nemo_nlp
      3 import nemo.collections.tts as nemo_tts

7 frames

[/usr/local/lib/python3.11/dist-packages/nemo/core/classes/mixins/hf_io_mixin.py](https://localhost:8080/#) in <module>
     17 from typing import Dict, Iterable, List, Optional, Union
     18 
---> 19 from huggingface_hub import HfApi, ModelCard, ModelCardData, ModelFilter
     20 from huggingface_hub import get_token as get_hf_token
     21 from huggingface_hub.hf_api import ModelInfo

ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' (/usr/local/lib/python3.11/dist-packages/huggingface_hub/__init__.py)


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

This is the full error I get in google colab even with the edits you have above

**Comment by philm001** [comment]
Ok, I think that I was able to kinda figure it out, I had to move the spot where it was calling the pip command. This is what worked for me. However, I have another error that i need to deal with. It is unrelated to this one:

```
!pip install transformers==4.40.0
!pip install huggingface_hub==0.21.3
!pip install tokenizers>=0.21
!pip install datasets==2.19.0

import nemo.collections.asr as nemo_asr
import nemo.collections.nlp as nemo_nlp
import nemo.collections.tts as nemo_tts
```

**Comment by d4551** [comment]
[Hugging Face](https://huggingface.co/)'s logo
Hugging Face
[Models](https://huggingface.co/models)
[Datasets](https://huggingface.co/datasets)
[Spaces](https://huggingface.co/spaces)
[Posts](https://huggingface.co/posts)
[Docs](https://huggingface.co/docs)
[Enterprise](https://huggingface.co/enterprise)
[Pricing](https://huggingface.co/pricing)



Hub Python Library

Hub Python Library

Search documentation
⌘K

v0.5.1

EN

 2,341
Guides
🤗 Hugging Face Hub Python Wrapper
How to download files from the hub
How to upload files to the hub
Searching the Hub
How to programmatically access the Inference API
Reference
Managing local and online repositories
Hugging Face Hub API
Downloading files
Mixins & serialization methods
Logging
You are viewing v0.5.1 version. A newer version v0.28.1 is available.
Searching the Hub Efficiently with Python
In this tutorial, we will explore how to interact and explore the Hugging Face Hub with the huggingface_hub library to help find available models and datasets quickly.

The Basics
huggingface_hub is a Python library that allows anyone to freely extract useful information from the Hub, as well as downloading and publishing models. You can install it with:

Copied
pip install huggingface_hub
It comes packaged with an interface that can interact with the Hub in the HfApi class:

Copied
from huggingface_hub import HfApi
api = HfApi()
This class lets you perform a variety of operations that interact with the raw Hub API. We’ll be focusing on two specific functions:

list_models
list_datasets
If you look at what can be passed into each function, you will find the parameter list looks something like:

filter
author
search
…
Two of these parameters are intuitive (author and search), but what about that filter? 🤔 Let’s dive into a few helpers quickly and revisit that question.

Search Parameters
The huggingface_hub provides a user-friendly interface to know what exactly can be passed into this filter parameter through the ModelSearchArguments and DatasetSearchArguments classes:

Copied
from huggingface_hub import ModelSearchArguments, DatasetSearchArguments

model_args = ModelSearchArguments()
dataset_args = DatasetSearchArguments()
These are nested namespace objects that have every single option available on the Hub and that will return what should be passed to filter. The best of all is: it has tab completion 🎊 .

Searching for a Model
Let’s pose a problem that would be complicated to solve without access to this information:

I want to search the Hub for all PyTorch models trained on the glue dataset that can do Text Classification.

If you check what is available in model_args by checking it’s output, you will find:

Copied
model_args
Available Attributes or Keys:

author
dataset
language
library
license
model_name
pipeline_tag
It has a variety of attributes or keys available to you. This is because it is both an object and a dictionary, so you can either do model_args["author"] or model_args.author. For this tutorial, let’s follow the latter format.

The first criteria is getting all PyTorch models. This would be found under the library attribute, so let’s see if it is there:

Copied
model_args.library
Available Attributes or Keys:

AdapterTransformers
Asteroid
ESPnet
Flair
JAX
Joblib
Keras
ONNX
PyTorch
Pyannote
Rust
Scikit_learn
SentenceTransformers
Stanza
TFLite
TensorBoard
TensorFlow
TensorFlowTTS
Timm
Transformers
allennlp
fastText
fastai
spaCy
speechbrain
It is! The PyTorch name is there, so you’ll need to use model_args.library.PyTorch:

Copied
model_args.library.PyTorch
‘pytorch’

Below is an animation repeating the process for finding both the Text Classification and glue requirements:

Animation exploring `model_args.pipeline_tag`

Animation exploring `model_args.dataset`

Now that all the pieces are there, the last step is to combine them all for something the API can use through the ModelFilter and DatasetFilter classes. The classes transform the outputs of the previous step into something the API can use conveniently:

Copied
from huggingface_hub import ModelFilter, DatasetFilter

filt = ModelFilter(
    task=args.pipeline_tag.TextClassification, 
    trained_dataset=args.dataset.glue, 
    library=args.library.PyTorch
)
api.list_models(filter=filt)[0]
ModelInfo: { modelId: 09panesara/distilbert-base-uncased-finetuned-cola sha: f89a85cb8703676115912fffa55842f23eb981ab lastModified: 2021-12-21T14:03:01.000Z tags: [‘pytorch’, ‘tensorboard’, ‘distilbert’, ‘text-classification’, ‘dataset:glue’, ‘transformers’, ‘license:apache-2.0’, ‘generated_from_trainer’, ‘model-index’, ‘infinity_compatible’] pipeline_tag: text-classification siblings: [ModelFile(rfilename=’.gitattributes’), ModelFile(rfilename=’.gitignore’), ModelFile(rfilename=‘README.md’), ModelFile(rfilename=‘config.json’), ModelFile(rfilename=‘pytorch_model.bin’), ModelFile(rfilename=‘special_tokens_map.json’), ModelFile(rfilename=‘tokenizer.json’), ModelFile(rfilename=‘tokenizer_config.json’), ModelFile(rfilename=‘training_args.bin’), ModelFile(rfilename=‘vocab.txt’), ModelFile(rfilename=‘runs/Dec21_13-51-40_bc62d5d57d92/events.out.tfevents.1640094759.bc62d5d57d92.77.0’), ModelFile(rfilename=‘runs/Dec21_13-51-40_bc62d5d57d92/events.out.tfevents.1640095117.bc62d5d57d92.77.2’), ModelFile(rfilename=‘runs/Dec21_13-51-40_bc62d5d57d92/1640094759.4067502/events.out.tfevents.1640094759.bc62d5d57d92.77.1’)] config: None private: False downloads: 6 library_name: transformers likes: 0 }

As you can see, it found the models that fit all the criteria. You can even take it further by passing in an array for each of the parameters from before. For example, let’s take a look for the same configuration, but also include TensorFlow in the filter:

Copied
filt = ModelFilter(
    task=args.pipeline_tag.TextClassification, 
    library=[args.library.PyTorch, args.library.TensorFlow]
)
api.list_models(filter=filt)[0]
ModelInfo: { modelId: CAMeL-Lab/bert-base-arabic-camelbert-ca-poetry sha: bc50b6dc1c97dc66998287efb6d044bdaa8f7057 lastModified: 2021-10-17T12:09:38.000Z tags: [‘pytorch’, ‘tf’, ‘bert’, ‘text-classification’, ‘ar’, ‘arxiv:1905.05700’, ‘arxiv:2103.06678’, ‘transformers’, ‘license:apache-2.0’, ‘infinity_compatible’] pipeline_tag: text-classification siblings: [ModelFile(rfilename=’.gitattributes’), ModelFile(rfilename=‘README.md’), ModelFile(rfilename=‘config.json’), ModelFile(rfilename=‘pytorch_model.bin’), ModelFile(rfilename=‘special_tokens_map.json’), ModelFile(rfilename=‘tf_model.h5’), ModelFile(rfilename=‘tokenizer_config.json’), ModelFile(rfilename=‘training_args.bin’), ModelFile(rfilename=‘vocab.txt’)] config: None private: False downloads: 21 library_name: transformers likes: 0 }

Searching for a Dataset
Similarly to finding a model, you can find a dataset easily by following the same steps.

The new scenario will be:

I want to search the Hub for all datasets that can be used for text_classification and are in English.

First, you should look at what is available in the DatasetSearchArguments, similar to the ModelSearchArguments:

Copied
dataset_args = DatasetSearchArguments()
dataset_args
Available Attributes or Keys:

author
benchmark
dataset_name
language_creators
languages
licenses
multilinguality
size_categories
task_categories
task_ids
text_classification is a task, so first you should check task_categories:

Copied
dataset_args.task_categories
Available Attributes or Keys:

Summarization
audio_classification
automatic_speech_recognition
code_generation
conditional_text_generation
cross_language_transcription
dialogue_system
grammaticalerrorcorrection
machine_translation
named_entity_disambiguation
named_entity_recognition
natural_language_inference
news_classification
other
other_test
other_text_search
paraphrase
paraphrasedetection
query_paraphrasing
question_answering
question_generation
sentiment_analysis
sequence_modeling
speech_processing
structure_prediction
summarization
text_classification
text_generation
text_retrieval
text_scoring
textual_entailment
translation
There you will find text_classification, so you should use dataset_args.task_categories.text_classification.

Next we need to find the proper language. There is a languages property we can check. These are two-letter language codes, so you should check if it has en:

Copied
"en" in dataset_args.languages
True

Now that the pieces are found, you can write a filter:

Copied
filt = DatasetFilter(
   languages=dataset_args.languages.en,
   task_categories=dataset_args.task_categories.text_classification
)
And search the API!

Copied
api.list_datasets(filter=filt)[0]
DatasetInfo: { id: Abirate/english_quotes lastModified: None tags: [‘annotations_creators:expert-generated’, ‘language_creators:expert-generated’, ‘language_creators:crowdsourced’, ‘languages:en’, ‘multilinguality:monolingual’, ‘source_datasets:original’, ‘task_categories:text-classification’, ‘task_ids:multi-label-classification’] private: False author: Abirate description: None citation: None cardData: None siblings: None gated: False }

With these two functionalities combined, you can search for all available parameters and tags within the Hub to search for with ease for both Datasets and Models!

←
[How to upload files to the hub](https://huggingface.co/docs/huggingface_hub/v0.5.1/en/how-to-upstream)
How to programmatically access the Inference API
→
[Searching the Hub](https://huggingface.co/docs/huggingface_hub/v0.5.1/en/searching-the-hub) Efficiently with Python
The Basics
Search Parameters
Searching for a Model
Searching for a Dataset

**Comment by djibe** [comment]
Hi @philm001 , how can this work as transformers and tokenizers are not compatible ?:

```
 The user requested tokenizers>=0.21
    transformers 4.40.0 depends on tokenizers<0.20 and >=0.19
```

**Comment by djibe** [comment]
As 2025-03-23, this works:

```
transformers==4.40.0
huggingface_hub==0.21.3
tokenizers
datasets==2.19.0
```

**Comment by rahma-muhammad** [comment]
> As 2025-03-23, this works:
> 
> ```
> transformers==4.40.0
> huggingface_hub==0.21.3
> tokenizers
> datasets==2.19.0
> ```

Thanks for inspiration!

As 9/9/2025 and while using peft to fine-tune the model as well, this worked for me:
transformers==4.56.1
huggingface_hub==0.34.4
tokenizers==0.22.0
datasets==3.6.0
peft==0.17.0
