### ISSUE TITLE
floor_divide missed in part of the code, throwing error while running using pre-trained model

### ISSUE THREAD

**Issue by savitha91** [NVIDIA/NeMo#985]
/usr/local/lib/python3.6/dist-packages/nemo_asr/parts/jasper.py in get_seq_len(self, lens)
     85     def get_seq_len(self, lens):
     86         return ((lens + 2 * self.conv.padding[0] - self.conv.dilation[0] * (
---> 87                 self.conv.kernel_size[0] - 1) - 1) / self.conv.stride[0] + 1)
     88 
     89     def forward(self, x, lens):

RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

Kindly let me know when can we get an update

**Comment by RemonComputer** [comment]
I had the same issue but I think I solved it by replacing the true division sign "/" with the integer division sign "//",
saved the file and the problem was solved, but I agree that this is a bug and should be fixed

**Comment by soheiltehranipour** [comment]
This Error happens because of latest version of PyTorch.
Recently PyTorch updgraded to 1.6 and in this version you will face this runtime error.

I had your issue too.
Simplest way is downgrading PyTorch with this command.

!pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

But keep in mind that after executing this command you should "Restart the Runtime".

**Comment by soheiltehranipour** [comment]
https://github.com/NVIDIA/NeMo/issues/981#issue-672832141

**Comment by pchitale1** [comment]
Thank you
